export function installBuilder(){
 const $=id=>document.getElementById(id),workspace=$('workspace');workspace.dataset.view='builder';
 const bar=document.createElement('div');bar.className='builder-bar';bar.innerHTML='<div><p class="eyebrow">QUOTATIONS / EDITOR</p><strong id="quoteState">New quotation · Draft</strong></div><div class="builder-switch" role="group" aria-label="Quotation view"><button type="button" data-view="builder" aria-pressed="true">1 · Builder</button><button type="button" data-view="review" aria-pressed="false">2 · Review &amp; share</button></div>';
 workspace.prepend(bar);
 const source=$('file').closest('section.panel');source.classList.add('builder-only','source-card');workspace.querySelector('.identity-panel').classList.add('builder-only');workspace.querySelector('.guide').classList.add('builder-only');workspace.querySelector('.workflow').classList.add('builder-only');
 const review=document.createElement('section');review.className='panel review-only';review.innerHTML='<h2>Customer document</h2><p class="hint">Review the saved customer-facing document below. Internal rates and margin are excluded. Use the actions beneath it to issue, download or share.</p><div id="reviewDocument"><p class="hint">Save a reviewed revision in Builder to preview it here.</p></div>';
 const aside=workspace.querySelector('.quote-layout>aside');aside.prepend(review);
 const browse=document.createElement('button');browse.type='button';browse.className='btn-app btn-app--secondary';browse.textContent='Browse saved profiles';$('loadProfile').after(browse);
 const picker=document.createElement('dialog');picker.className='profile-picker';picker.setAttribute('aria-label','Choose saved costing profile');picker.innerHTML='<header><h2>Choose saved costing profile</h2><button type="button" class="btn-app btn-app--secondary" data-close>Close</button></header><label>Search profiles<input type="search" placeholder="Customer, machine, gas or electricity"></label><p class="hint">Select a profile to load its saved settings. Review currency and compatibility before calculating.</p><div class="profile-picker-results"></div>';
 document.body.append(picker);const renderProfiles=()=>{const list=picker.querySelector('.profile-picker-results');list.replaceChildren();const term=picker.querySelector('input').value.trim().toLowerCase();for(const option of $('profile').options){if(!option.value||!option.textContent.toLowerCase().includes(term))continue;const button=document.createElement('button');button.type='button';button.className='profile-choice';button.textContent=option.textContent;button.onclick=()=>{$('profile').value=option.value;picker.close();$('loadProfile').click();browse.focus()};list.append(button)}if(!list.children.length)list.textContent='No matching profiles. Save reusable standards in Builder first.'};browse.onclick=()=>{picker.querySelector('input').value='';renderProfiles();picker.showModal();picker.querySelector('input').focus()};picker.querySelector('input').oninput=renderProfiles;picker.querySelector('[data-close]').onclick=()=>picker.close();
 const filters=document.createElement('div');filters.className='quote-list-filters';filters.innerHTML='<label>Search quotations<input type="search" placeholder="Customer, quote number or reference"></label><label>Status<select><option value="">All statuses</option><option>draft</option><option>issued</option><option>accepted</option><option>declined</option><option>expired</option></select></label><p role="status"></p>';$('quoteList').before(filters);
 const filterQuotes=()=>{const term=filters.querySelector('input').value.trim().toLowerCase(),status=filters.querySelector('select').value;const rows=[...$('quoteList').querySelectorAll('tbody tr')].filter(r=>r.querySelector('[data-quote]'));let shown=0;for(const row of rows){row.hidden=!row.textContent.toLowerCase().includes(term)||(!!status&&row.cells[3]?.textContent.trim()!==status);if(!row.hidden)shown++}filters.querySelector('[role=status]').textContent=rows.length?shown+' of '+rows.length+' revisions shown':''};filters.oninput=filterQuotes;filters.onchange=filterQuotes;new MutationObserver(filterQuotes).observe($('quoteList'),{childList:true,subtree:true});
 const next=document.createElement('button');next.type='button';next.className='btn-app builder-only';next.textContent='Continue to review →';next.onclick=()=>setView('review');$('result').after(next);
 function setView(view){workspace.dataset.view=view;bar.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));if(view==='builder')return;bar.scrollIntoView({block:'start',behavior:'instant'})}
 bar.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.addEventListener('quote-view',e=>setView(e.detail));$('newQuote').addEventListener('click',()=>setView('builder'));
 // Reveal collapsed fields for browser validation and tutorial navigation.
 $('quoteForm').addEventListener('invalid',e=>{setView('builder');for(let parent=e.target.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true},true);
 document.addEventListener('click',e=>{if(e.target.closest('#startWalkthrough'))setView('builder')},true);
}
