export function customerPicker({root,field,get,post,profiles,changed}){
 let customers=[],loaded=false,selected='',busy=false
 root.innerHTML='<div class="fields"><label>Search saved customers · optional<input type="search" id="customerSearch" placeholder="Search company name" autocomplete="off"></label><label>Saved customer / organization · optional<select id="savedCustomer"><option value="">Choose a customer</option></select></label></div><div class="customer-tools"><button type="button" id="saveCustomerName" class="btn-app btn-app--secondary">Save as new customer</button><button type="button" id="refreshCustomers" class="btn-app btn-app--secondary">Refresh customers</button></div><p class="hint" id="customerPickerStatus" role="status"></p>'
 const search=root.querySelector('input'),select=root.querySelector('select'),status=root.querySelector('[role=status]'),save=root.querySelector('#saveCustomerName'),refresh=root.querySelector('#refreshCustomers')
 const entries=()=>{const names=new Map();for(const c of customers){if(c.name)names.set(c.name.trim().toLowerCase(),c.name.trim())}for(const p of profiles()){if(p.rates?._profile?.kind==='customer'){const name=p.rates._profile.customer||p.name;if(name)names.set(name.trim().toLowerCase(),name.trim())}}return [...names.values()].sort((a,b)=>a.localeCompare(b))}
 const render=()=>{const matches=entries().filter(n=>n.toLowerCase().includes(search.value.trim().toLowerCase()));select.replaceChildren(new Option(matches.length?'Choose a customer':'No matching saved customers',''));for(const n of matches)select.add(new Option(n,n));select.value=matches.includes(selected)?selected:''}
 const load=async()=>{refresh.disabled=true;try{customers=await get('/api/settings?resource=customers');loaded=true;render();status.textContent=entries().length?'Select a saved company, or enter a new one below. Selecting a company does not change your rates.':'No saved customers yet. Enter the organization name below and save it for next time.'}catch(_){loaded=false;status.textContent='Could not load the customer directory. You can still enter a name. Refresh before saving a new customer.'}finally{refresh.disabled=false}}
 search.addEventListener('input',e=>{e.stopPropagation();render()});select.addEventListener('change',()=>{if(!select.value)return;selected=select.value;field.value=selected;changed();status.textContent='Customer selected. Quotation rates are unchanged; load a customer profile separately if needed.'})
 field.addEventListener('input',()=>{selected='';select.value=''})
 save.onclick=async()=>{if(busy)return;const name=field.value.trim();if(!name){status.textContent='Enter the customer / organization name first.';field.focus();return}if(!loaded){status.textContent='Refresh the customer directory before saving.';return}if(customers.some(c=>c.name.trim().toLowerCase()===name.toLowerCase())){status.textContent='This customer is already saved.';return}busy=true;save.disabled=true;try{const row=await post('/api/settings?resource=customers',{name});customers.push(row);selected=name;search.value='';render();status.textContent='Customer saved to your company directory for future quotations.'}catch(e){status.textContent=e.message||'Could not save customer. Please try again.'}finally{busy=false;save.disabled=false}}
 refresh.onclick=load;load();return render
}
