import { requireAuth } from '../../_shared/auth.js'
import { renderNav } from '../../_shared/nav.js'
import { hasModule } from '../../_shared/modules.js'
import { apiGet, apiPost } from '../../_shared/api.js'
const session=requireAuth(), $=id=>document.getElementById(id), form=$('quoteForm')
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
let imported=null, current=null, profiles=[], dirty=false, busy=false, requestId=crypto.randomUUID()
const sections=[
  {title:'Calculation method',hint:'Use shop costs for a new estimate, or compare Han’s configured charges. All prices use the selected currency; no exchange conversion is applied.',fields:[['method','Basis','select',[['shop','Shop cost estimate'],['hans','Han’s charge comparison']]]] },
  {title:'Material and machine',when:r=>r.method==='shop',hint:'Full-sheet pricing. Machine hourly cost must exclude gas, electricity or labor entered separately below.',fields:[['materialMode','Material pricing','select',[['sheet','Price per full sheet'],['kg','Price per kg'],['customer','Customer supplies material']]],['sheetPrice','Price per sheet','number',null,r=>r.materialMode==='sheet'],['pricePerKg','Material price per kg','number',null,r=>r.materialMode==='kg'],['density','Density (g/cm³)','number',null,r=>r.materialMode==='kg'],['remnantCredit','Remnant credit',0],['machineHourly','Machine cost per hour','number'],['setupMinutes','Setup minutes',0],['setupHourly','Setup labor cost per hour','number'],['laborMinutes','Additional labor minutes',0],['laborHourly','Additional labor cost per hour','number']]},
  {title:'Gas',hint:'Bottle volume is supplier-stated standard m³ of gas, not cylinder water capacity. Cutting and piercing flow must use the same standard-volume convention. Additional gas-on seconds use the cutting flow rate; travel is excluded.',fields:[['gasMode','Gas pricing','select',[['pack','Bottle / bottle pack'],['unit','Price per standard m³'],['manual','Manual job gas charge'],['included','Included elsewhere / explicitly excluded']]],['packPrice','Refill / pack price','number',null,r=>r.gasMode==='pack'],['bottles','Bottles per pack','number',null,r=>r.gasMode==='pack'],['volumePerBottle','Gas per bottle (standard m³)','number',null,r=>r.gasMode==='pack'],['usablePct','Usable gas (%)','number',null,r=>r.gasMode==='pack'],['gasUnitPrice','Price per standard m³','number',null,r=>r.gasMode==='unit'],['gasFlowLmin','Cutting flow (standard L/min)','number',null,r=>['pack','unit'].includes(r.gasMode)],['pierceFlowLmin','Piercing flow (standard L/min)','number',null,r=>['pack','unit'].includes(r.gasMode)],['purgeSeconds','Additional gas-on seconds',0,null,r=>['pack','unit'].includes(r.gasMode)],['gasManualCost','Job gas charge','number',null,r=>r.gasMode==='manual'],['gasReason','Where included, or reason excluded','text',null,r=>r.gasMode==='included']]},
  {title:'Electricity',hint:'Use average electrical input, not laser optical power. The pilot applies this load to processing plus entered setup time. Include auxiliaries once; avoid counting compressor or gas-generator power twice.',fields:[['electricityMode','Electricity calculation','select',[['estimate','Average electrical load × time'],['manual','Manual job electricity charge'],['included','Included elsewhere / explicitly excluded']]],['powerKw','Average electrical input (kW)','number',null,r=>r.electricityMode==='estimate'],['energyPrice','Electricity price per kWh','number',null,r=>r.electricityMode==='estimate'],['electricityManualCost','Job electricity charge','number',null,r=>r.electricityMode==='manual'],['electricityReason','Where included, or reason excluded','text',null,r=>r.electricityMode==='included']]},
  {title:'Other costs and selling price',hint:'Margin is a share of selling price. Markup is added to the cost basis. Taxes are excluded from this pilot quotation.',fields:[['otherCost','Other operations / overhead',0],['pricing','Selling-price method','select',[['margin','Target margin'],['markup','Markup on basis']]],['percentage','Margin / markup (%)','number'],['minimumCharge','Minimum selling charge',0]]}
]
function rates(){const data=Object.fromEntries(new FormData(form));const r={currency:data.currency};for(const section of sections)for(const [key] of section.fields)r[key]=data[key]??'';return r}
function buildFields(){
  $('rateFields').innerHTML=sections.map((section,i)=>`<section class="rate-section" data-section="${i}"><h3>${esc(section.title)}</h3><p class="hint">${esc(section.hint)}</p><div class="fields">${section.fields.map(([key,label,type,options])=>`<label data-field="${key}">${esc(label)}${type==='select'?`<select name="${key}">${options.map(([value,text])=>`<option value="${value}">${esc(text)}</option>`).join('')}</select>`:`<input name="${key}" type="${type==='text'?'text':'number'}" ${type==='text'?'maxlength="300"':'min="0" max="100000000" step="any"'} ${typeof type==='number'?`value="${type}"`:''}>`}</label>`).join('')}</div></section>`).join('')
  visibility()
}
function visibility(){const r=rates();sections.forEach((section,i)=>{document.querySelector(`[data-section="${i}"]`).hidden=section.when?!section.when(r):false;section.fields.forEach(([key,,, ,when])=>{document.querySelector(`[data-field="${key}"]`).hidden=when?!when(r):false})})}
function money(value,currency){return value==null?'Not estimated':new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(value)}
function message(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'success'}
async function run(task){if(busy)return;busy=true;$('workspace').inert=true;$('newQuote').disabled=true;try{await task()}catch(e){message(e.message,true)}finally{busy=false;$('workspace').inert=false;$('newQuote').disabled=false}}
function markDirty(event){dirty=true;requestId=crypto.randomUUID();if(event?.target?.name!=='reviewed')form.elements.reviewed.checked=false;$('quoteActions').hidden=true;$('customerPrint').innerHTML='';if(imported)$('result').innerHTML='<p class="warning">Settings changed. Calculate again to see the current estimate.</p>';visibility()}
function sourceView(){
  const s=imported?.source;if(!s){$('sourceSummary').innerHTML='';$('sourceWarnings').innerHTML='';$('parts').innerHTML='';return}
  $('sourceSummary').innerHTML=`<p class="hint">${esc(s.sourceName)} · ${esc(s.program)}</p><div class="source-stats"><div><b>${esc(s.material)} / ${s.thicknessMm} mm</b><span>${esc(s.gas)} · ${s.sheetWidthMm} × ${s.sheetHeightMm} mm</span></div><div><b>${s.parts.reduce((n,p)=>n+p.nested,0)} parts</b><span>${s.pierces} pierces</span></div><div><b>${(s.totalSeconds/60).toFixed(3)} min</b><span>Imported processing time</span></div><div><b>${s.charges.total.toFixed(2)}</b><span>Han’s total · confirm currency below</span></div></div><p class="hint">Used size ${s.usedWidthMm} × ${s.usedHeightMm} mm · utilization ${s.utilizationPct}% · reported parts weight ${s.partsWeightKg} kg.</p>`
  $('sourceWarnings').innerHTML=s.warnings.map(w=>`<p class="warning">${esc(w)}</p>`).join('')
  $('parts').innerHTML=`<table><thead><tr><th>Part</th><th>Size (mm)</th><th>Requested</th><th>Nested</th><th>Pierces / part</th></tr></thead><tbody>${s.parts.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.widthMm} × ${p.heightMm}</td><td>${p.requested}</td><td>${p.nested}</td><td>${p.pierces}</td></tr>`).join('')}</tbody></table>`
}
function resultView(result){
  $('result').innerHTML=`${current&&!dirty?`<p class="hint">LQ-${esc(current.family_id.slice(0,8).toUpperCase())} · Rev ${current.revision} · ${esc(current.status)}</p>`:''}${result.components.map(c=>`<div class="breakdown"><span>${esc(c.name)}</span><b>${money(c.amount,result.currency)}</b></div>`).join('')}<p class="hint">${result.rates.method==='hans'?'Configured charge basis':'Estimated cost'}: ${money(result.basis,result.currency)}</p><p class="price">${money(result.price,result.currency)}</p><p class="hint">${esc(result.currency)} · ${result.quantity} nested parts · tax excluded${result.margin==null?'':` · ${result.margin}% ${result.rates.method==='hans'?'difference from basis':'margin'}`}</p>${Object.entries(result.usage).map(([key,v])=>`<p class="hint">${esc({sheetKg:'Full stock kg',packUsableM3:'Usable pack standard m³',gasM3:'Estimated gas standard m³',gasPerM3:'Gas price per standard m³',energyKwh:'Estimated electricity kWh'}[key])}: ${v}</p>`).join('')}${result.missing.length?`<div class="warning"><b>Still needed</b><ul>${result.missing.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`:''}${result.warnings.map(w=>`<p class="warning">${esc(w)}</p>`).join('')}`
  $('quoteActions').hidden=!current||dirty
  $('issueQuote').hidden=current?.status!=='draft';$('acceptQuote').hidden=current?.status!=='issued'
}
async function refresh(){const rows=await apiGet('/api/laser-quotes?action=quotes');$('quoteList').innerHTML=rows.length?`<table><thead><tr><th>Quote</th><th>Customer</th><th>Reference</th><th>Status</th><th>Total</th><th>Saved</th></tr></thead><tbody>${rows.map(q=>`<tr><td><button class="inline-button" data-quote="${esc(q.id)}">LQ-${esc(q.family_id.slice(0,8).toUpperCase())} / ${q.revision}</button></td><td>${esc(q.customer)}</td><td>${esc(q.reference)}</td><td>${esc(q.status)}</td><td>${money(q.price,q.currency)}</td><td>${esc(new Date(q.created_at).toLocaleDateString())}</td></tr>`).join('')}</tbody></table>`:'<p class="hint">No saved quotations yet. Import a report to begin.</p>'}
function fill(values){for(const [key,value]of Object.entries(values)){const el=form.elements.namedItem(key);if(el&&el.type!=='checkbox')el.value=value??''}visibility()}
async function loadQuote(id){current=await apiGet('/api/laser-quotes?action=quotes&id='+encodeURIComponent(id));imported={id:current.import_id,source:current.source};fill({...current.result.rates,customer:current.customer,reference:current.reference,valid_days:current.valid_days,terms:current.terms});form.elements.reviewed.checked=false;dirty=false;sourceView();resultView(current.result);requestId=crypto.randomUUID();message('Saved revision opened. Editing and saving creates a new revision.');window.scrollTo({top:0,behavior:'smooth'})}
function printQuote(){if(!current||dirty)return;const q=current,s=q.source;const date=q.issued_at||q.created_at;const expiry=new Date(new Date(date).getTime()+q.valid_days*86400000);$('customerPrint').innerHTML=`<h1>${esc(session.account.name)} — Quotation</h1><p><strong>LQ-${esc(q.family_id.slice(0,8).toUpperCase())} · Revision ${q.revision}${q.status==='draft'?' · DRAFT':''}</strong><br>Date: ${esc(new Date(date).toLocaleDateString())}<br>Valid through: ${esc(expiry.toLocaleDateString())}</p><p>Prepared for: <strong>${esc(q.customer)}</strong><br>Reference: ${esc(q.reference||'—')}</p><p>${esc(s.material)} · ${s.thicknessMm} mm · laser cutting</p><table><thead><tr><th>Part</th><th>Size (mm)</th><th>Quantity</th></tr></thead><tbody>${s.parts.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.widthMm} × ${p.heightMm}</td><td>${p.nested}</td></tr>`).join('')}</tbody></table><p class="print-total">Batch total: ${money(q.result.price,q.result.currency)} ${esc(q.result.currency)}</p><p>Taxes excluded. Price applies to the complete batch and quantities shown.</p><p class="print-terms">${esc(q.terms)}</p>`;window.print()}
function reset(){current=null;imported=null;dirty=false;requestId=crypto.randomUUID();form.reset();buildFields();sourceView();$('file').value='';$('quoteActions').hidden=true;$('customerPrint').innerHTML='';$('result').innerHTML='<p class="hint">Import a report and enter your rates.</p>';message('New quote started.')}
if(session){
  renderNav('/app/modules/laser-quoting/')
  $('mobileNavBtn').onclick=()=>$('app-nav').classList.toggle('open')
  if(!hasModule(session.account,'laser-quoting')||!['owner','admin','manager'].includes(session.role)){message('Laser Quoting is available to owners, admins and managers with pilot access.',true)}
  else{
    $('workspace').hidden=false;buildFields();$('profileEditor').hidden=!['owner','admin'].includes(session.role)
    run(async()=>{profiles=await apiGet('/api/laser-quotes?action=profiles');$('profile').innerHTML='<option value="">Choose a profile</option>'+profiles.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');await refresh()})
    form.addEventListener('input',markDirty);form.addEventListener('change',visibility)
    $('file').onchange=()=>run(async()=>{const file=$('file').files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Choose a file under 2 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Could not read the selected file.'));reader.readAsDataURL(file)});const result=await apiPost('/api/laser-quotes?action=import',{file:base64,name:file.name});imported=result;markDirty();form.elements.reviewed.checked=false;sourceView();message(result.duplicate?'This report was already imported. Its existing source record has been reused.':'Report imported. Review the source and enter your shop’s costing settings.')})
    form.onsubmit=e=>{e.preventDefault();run(async()=>{if(!imported)throw Error('Import a Han’s report first.');const result=await apiPost('/api/laser-quotes?action=calculate',{import_id:imported.id,rates:rates()});resultView(result);message(result.complete?'Calculation complete. Review and save your quotation.':'Complete the missing settings listed in the breakdown.',!result.complete)})}
    $('saveQuote').onclick=()=>run(async()=>{if(!imported)throw Error('Import a Han’s report first.');if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));current=await apiPost('/api/laser-quotes?action=save',{import_id:imported.id,request_id:requestId,previous_id:current?.id||null,rates:rates(),customer:values.customer,reference:values.reference,terms:values.terms,valid_days:Number(values.valid_days),reviewed:form.elements.reviewed.checked});dirty=false;requestId=crypto.randomUUID();resultView(current.result);await refresh();message('Quote revision saved. You can print it or mark it issued.')})
    $('loadProfile').onclick=()=>{const profile=profiles.find(p=>p.id===$('profile').value);if(profile){fill(profile.rates);markDirty();message('Profile loaded. Check job-specific setup, labor and other costs.')}}
    $('saveProfile').onclick=()=>run(async()=>{const profile=await apiPost('/api/laser-quotes?action=profiles',{name:$('profileName').value,rates:rates()});profiles.push(profile);const option=document.createElement('option');option.value=profile.id;option.textContent=profile.name;$('profile').append(option);$('profile').value=profile.id;message('New shop profile saved.')})
    for(const [id,status]of [['issueQuote','issued'],['acceptQuote','accepted']])$(id).onclick=()=>run(async()=>{if(!current||dirty)throw Error('Save this revision first.');current=await apiPost('/api/laser-quotes?action=status',{id:current.id,status});resultView(current.result);await refresh();message(status==='issued'?'Revision marked issued. No email has been sent.':'Acceptance recorded. Job creation is not yet part of this pilot.')})
    $('quoteList').onclick=e=>{const button=e.target.closest('[data-quote]');if(button)run(()=>loadQuote(button.dataset.quote))}
    $('refreshList').onclick=()=>run(refresh);$('printQuote').onclick=printQuote
    $('newQuote').onclick=()=>{if(!dirty||window.confirm('Discard the unsaved changes and start a new quote?'))reset()}
  }
}
