import { installBuilder } from './builder.js'
import { customerPicker } from './customers.js'
import { workflow } from './workflow.js'
import { draftController } from './draft.js'
import { requireAuth } from '../../_shared/auth.js'
import { renderNav } from '../../_shared/nav.js'
import { hasModule } from '../../_shared/modules.js'
import { apiGet, apiPost } from '../../_shared/api.js'
const session=requireAuth(), $=id=>document.getElementById(id), form=$('quoteForm')
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
let imported=null, current=null, profiles=[], dirty=false, busy=false, requestId=crypto.randomUUID()
let guided=null, refreshCustomerPicker=()=>{}
const drafts=draftController({get:apiGet,post:apiPost,notice:message,
 capture:()=>({import_id:imported?.id||null,previous_id:current?.id||null,values:{...Object.fromEntries(new FormData(form)),reviewed:undefined,profileCustomer:$('profileCustomer').value,profileMachine:$('profileMachine').value}}),
 restore:async p=>{if(p.previous_id)await loadQuote(p.previous_id);else current=null;imported=p.import_id?await apiGet('/api/laser-quotes?action=source&id='+encodeURIComponent(p.import_id)):null;fill(p.values);$('profileCustomer').value=p.values.profileCustomer||'';$('profileMachine').value=p.values.profileMachine||'';form.elements.reviewed.checked=false;dirty=true;requestId=crypto.randomUUID();sourceView();$('quoteActions').hidden=true;$('result').textContent='Recovered draft. Calculate and review before saving a revision.';guided?.resetReview()}
})
const sections=[
  {title:'Calculation method',hint:'Use shop costs for a new estimate, or compare Han’s configured charges. All prices use the selected currency; no exchange conversion is applied.',fields:[['method','Basis','select',[['shop','Shop cost estimate'],['hans','Han’s charge comparison']]]] },
  {title:'Material and machine',when:r=>r.method==='shop',hint:'Full-sheet pricing. Machine hourly cost must exclude gas, electricity or labor entered separately below.',fields:[['materialMode','Material pricing','select',[['sheet','Price per full sheet'],['kg','Price per kg'],['customer','Customer supplies material']]],['sheetPrice','Price per sheet','number',null,r=>r.materialMode==='sheet'],['pricePerKg','Material price per kg','number',null,r=>r.materialMode==='kg'],['density','Density (g/cm³)','number',null,r=>r.materialMode==='kg'],['remnantCredit','Remnant credit',0],['machineHourly','Machine cost per hour','number'],['setupMinutes','Setup minutes',0],['setupHourly','Setup labor cost per hour','number'],['laborMinutes','Additional labor minutes',0],['laborHourly','Additional labor cost per hour','number']]},
  {title:'Gas',hint:'Bottle volume is supplier-stated standard m³ of gas, not cylinder water capacity. Cutting and piercing flow must use the same standard-volume convention. Additional gas-on seconds use the cutting flow rate; travel is excluded.',fields:[['gasMode','Gas pricing','select',[['pack','Bottle / bottle pack'],['unit','Price per standard m³'],['manual','Manual job gas charge'],['included','Included elsewhere / explicitly excluded']]],['packPrice','Refill / pack price','number',null,r=>r.gasMode==='pack'],['bottles','Bottles per pack','number',null,r=>r.gasMode==='pack'],['volumePerBottle','Gas per bottle (standard m³)','number',null,r=>r.gasMode==='pack'],['usablePct','Usable gas (%)','number',null,r=>r.gasMode==='pack'],['gasUnitPrice','Price per standard m³','number',null,r=>r.gasMode==='unit'],['gasFlowLmin','Cutting flow (standard L/min)','number',null,r=>['pack','unit'].includes(r.gasMode)],['pierceFlowLmin','Piercing flow (standard L/min)','number',null,r=>['pack','unit'].includes(r.gasMode)],['purgeSeconds','Additional gas-on seconds',0,null,r=>['pack','unit'].includes(r.gasMode)],['gasManualCost','Job gas charge','number',null,r=>r.gasMode==='manual'],['gasReason','Where included, or reason excluded','text',null,r=>r.gasMode==='included']]},
  {title:'Electricity',hint:'Use average electrical input, not laser optical power. The pilot applies this load to processing plus entered setup time. Include auxiliaries once; avoid counting compressor or gas-generator power twice.',fields:[['electricityMode','Electricity calculation','select',[['estimate','Average electrical load × time'],['manual','Manual job electricity charge'],['included','Included elsewhere / explicitly excluded']]],['powerKw','Average electrical input (kW)','number',null,r=>r.electricityMode==='estimate'],['energyPrice','Electricity price per kWh','number',null,r=>r.electricityMode==='estimate'],['electricityManualCost','Job electricity charge','number',null,r=>r.electricityMode==='manual'],['electricityReason','Where included, or reason excluded','text',null,r=>r.electricityMode==='included']]},
  {title:'Other costs and selling price',hint:'Margin is a share of selling price. Markup is added to the cost basis. Taxes are excluded from this pilot quotation.',fields:[['otherCost','Other operations / overhead',0],['pricing','Selling-price method','select',[['margin','Target margin'],['markup','Markup on basis']]],['percentage','Margin / markup (%)','number'],['minimumCharge','Minimum selling charge',0]]}
]
function rates(){const data=Object.fromEntries(new FormData(form));const r={currency:data.currency};for(const section of sections)for(const [key] of section.fields)r[key]=data[key]??'';for(const key of ['remnantCredit','setupMinutes','laborMinutes','purgeSeconds','otherCost','minimumCharge'])if(r[key]==='')r[key]='0';return r}
function buildFields(){
  $('rateFields').innerHTML=sections.map((section,i)=>`<details ${i<2?'open':''} class="rate-section" data-section="${i}"><summary><span class="cost-number">${String(i+1).padStart(2,'0')}</span>${esc(section.title)}<span class="cost-expand" aria-hidden="true">+</span></summary><p class="hint">${esc(section.hint)}</p><div class="fields">${section.fields.map(([key,label,type,options])=>`<label data-field="${key}">${esc(label)}${type==='select'?`<select name="${key}">${options.map(([value,text])=>`<option value="${value}">${esc(text)}</option>`).join('')}</select>`:`<input name="${key}" type="${type==='text'?'text':'number'}" ${type==='text'?'maxlength="300"':'min="0" max="100000000" step="any"'} ${typeof type==='number'?`value="${type}"`:''}>`}</label>`).join('')}</div></details>`).join('')
  visibility()
  decorateFields()
}
function visibility(){const r=rates();sections.forEach((section,i)=>{document.querySelector(`[data-section="${i}"]`).hidden=section.when?!section.when(r):false;section.fields.forEach(([key,,, ,when])=>{document.querySelector(`[data-field="${key}"]`).hidden=when?!when(r):false})});updateRequirements()}
function money(value,currency){return value==null?'Not estimated':new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(value)}
function message(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'success'}
async function run(task){if(busy)return;busy=true;$('workspace').inert=true;$('newQuote').disabled=true;try{await task()}catch(e){message(e.message,true)}finally{busy=false;$('workspace').inert=false;$('newQuote').disabled=false;guided?.update()}}
function markDirty(event){guided?.invalidate();drafts.changed();if(event?.target?.dataset.origin){delete event.target.dataset.origin;event.target.closest('label')?.querySelector('.autofill-note')?.remove()}dirty=true;requestId=crypto.randomUUID();if(event?.target?.name!=='reviewed')form.elements.reviewed.checked=false;$('quoteActions').hidden=true;$('customerPrint').innerHTML='';if(imported)$('result').innerHTML='<p class="warning">Settings changed. Calculate again to see the current estimate.</p>';visibility();guided?.update()}
function sourceView(){
  const s=imported?.source;if(!s){$('sourceSummary').innerHTML='';$('sourceWarnings').innerHTML='';$('parts').innerHTML='';return}
  $('sourceSummary').innerHTML=`<p class="hint">${esc(s.sourceName)} · ${esc(s.program)}</p><div class="source-stats"><div><b>${esc(s.material)} / ${s.thicknessMm} mm</b><span>${esc(s.gas)} · ${s.sheetWidthMm} × ${s.sheetHeightMm} mm</span></div><div><b>${s.parts.reduce((n,p)=>n+p.nested,0)} parts</b><span>${s.pierces} pierces</span></div><div><b>${(s.totalSeconds/60).toFixed(3)} min</b><span>Imported processing time</span></div><div><b>${s.charges.total.toFixed(2)}</b><span>Han’s total · confirm currency below</span></div></div><p class="hint">Used size ${s.usedWidthMm} × ${s.usedHeightMm} mm · utilization ${s.utilizationPct}% · reported parts weight ${s.partsWeightKg} kg.</p>`
  $('sourceWarnings').innerHTML=s.warnings.map(w=>`<p class="warning">${esc(w)}</p>`).join('')
  $('parts').innerHTML=`<table><thead><tr><th>Part</th><th>Size (mm)</th><th>Requested</th><th>Nested</th><th>Pierces / part</th></tr></thead><tbody>${s.parts.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.widthMm} × ${p.heightMm}</td><td>${p.requested}</td><td>${p.nested}</td><td>${p.pierces}</td></tr>`).join('')}</tbody></table>`
}
function resultView(result){
  guided?.update(result)
  $('result').innerHTML=`${current&&!dirty?`<p class="hint">LQ-${esc(current.family_id.slice(0,8).toUpperCase())} · Rev ${current.revision} · ${esc(current.status)}</p>`:''}${result.components.map(c=>`<div class="breakdown"><span>${esc(c.name)}</span><b>${money(c.amount,result.currency)}</b></div>`).join('')}<p class="hint">${result.rates.method==='hans'?'Configured charge basis':'Estimated cost'}: ${money(result.basis,result.currency)}</p><p class="price">${money(result.price,result.currency)}</p><p class="hint">${esc(result.currency)} · ${result.quantity} nested parts · tax excluded${result.margin==null?'':` · ${result.margin}% ${result.rates.method==='hans'?'difference from basis':'margin'}`}</p>${Object.entries(result.usage).map(([key,v])=>`<p class="hint">${esc({sheetKg:'Full stock kg',packUsableM3:'Usable pack standard m³',gasM3:'Estimated gas standard m³',gasPerM3:'Gas price per standard m³',energyKwh:'Estimated electricity kWh'}[key])}: ${v}</p>`).join('')}${result.missing.length?`<div class="warning"><b>Still needed</b><ul>${result.missing.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`:''}${result.warnings.map(w=>`<p class="warning">${esc(w)}</p>`).join('')}`
  $('quoteActions').hidden=!current||dirty
  $('issueQuote').hidden=current?.status!=='draft';$('acceptQuote').hidden=current?.status!=='issued';$('declineQuote').hidden=current?.status!=='issued';$('expireQuote').hidden=current?.status!=='issued'||!expired(current);$('acceptQuote').disabled=expired(current)
}
function expired(q){return q?.status==='issued'&&Date.now()>=Date.parse(q.issued_at)+q.valid_days*86400000}
async function refresh(){const rows=await apiGet('/api/laser-quotes?action=quotes');$('quoteList').innerHTML=rows.length?`<table><thead><tr><th>Quote</th><th>Customer</th><th>Reference</th><th>Status</th><th>Total</th><th>Saved</th></tr></thead><tbody>${rows.map(q=>`<tr><td><button class="inline-button" data-quote="${esc(q.id)}">LQ-${esc(q.family_id.slice(0,8).toUpperCase())} / ${q.revision}</button></td><td>${esc(q.customer)}</td><td>${esc(q.reference)}</td><td>${expired(q)?'expired · renewal needed':esc(q.status)}</td><td>${money(q.price,q.currency)}</td><td>${esc(new Date(q.created_at).toLocaleDateString())}</td></tr>`).join('')}</tbody></table>`:'<p class="hint">No saved quotations yet. Import a report to begin.</p>'}
function fill(values){for(const [key,value]of Object.entries(values)){const el=form.elements.namedItem(key);if(el&&el.type!=='checkbox'){el.value=value??'';delete el.dataset.origin;el.closest('label')?.querySelector('.autofill-note')?.remove()}}visibility()}
async function loadQuote(id){$('customerPrint').innerHTML='';current=await apiGet('/api/laser-quotes?action=quotes&id='+encodeURIComponent(id));imported={id:current.import_id,source:current.source};fill({...current.result.rates,customer:current.customer,reference:current.reference,valid_days:current.valid_days,terms:current.terms});$('profileCustomer').value=current.result.profiles?.customer_id?.id||'';$('profileMachine').value=current.result.profiles?.machine_id?.id||'';form.elements.reviewed.checked=false;dirty=false;sourceView();resultView(current.result);requestId=crypto.randomUUID();guided?.restoreReview();message('Saved revision opened. Editing and saving creates a new revision.');window.scrollTo({top:0,behavior:'smooth'})}
function printQuote(){if(!current||dirty)return;const q=current,s=q.source;const date=q.issued_at||q.created_at;const expiry=new Date(new Date(date).getTime()+q.valid_days*86400000);$('customerPrint').innerHTML=`<h1>${esc(session.account.name)} — Quotation</h1><p><strong>LQ-${esc(q.family_id.slice(0,8).toUpperCase())} · Revision ${q.revision}${q.status==='draft'?' · DRAFT':''}</strong><br>Date: ${esc(new Date(date).toLocaleDateString())}<br>Valid through: ${esc(expiry.toLocaleDateString())}</p><p>Prepared for: <strong>${esc(q.customer)}</strong><br>Reference: ${esc(q.reference||'—')}</p><p>${esc(s.material)} · ${s.thicknessMm} mm · laser cutting</p><table><thead><tr><th>Part</th><th>Size (mm)</th><th>Quantity</th></tr></thead><tbody>${s.parts.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.widthMm} × ${p.heightMm}</td><td>${p.nested}</td></tr>`).join('')}</tbody></table><p class="print-total">Batch total: ${money(q.result.price,q.result.currency)} ${esc(q.result.currency)}</p><p>Taxes excluded. Price applies to the complete batch and quantities shown.</p><p>How this quote is prepared: material requirements and the imported production report inform processing time and estimated utility use. Setup, any additional operations and commercial terms are reflected in the batch price. Utility use is estimated; the quote applies to the quantities and material shown.</p><p class="print-terms">${esc(q.terms)}</p>`;window.print()}
function reset(){current=null;imported=null;dirty=false;requestId=crypto.randomUUID();form.reset();document.querySelectorAll('[data-origin]').forEach(e=>delete e.dataset.origin);document.querySelectorAll('.autofill-note').forEach(e=>e.remove());buildFields();sourceView();$('file').value='';$('quoteActions').hidden=true;$('customerPrint').innerHTML='';$('result').innerHTML='<p class="hint">Import a report and enter your rates.</p>';guided?.invalidate();message('New quote started.')}
if(session){
  renderNav('/app/modules/laser-quoting/')
  $('mobileNavBtn').onclick=()=>$('app-nav').classList.toggle('open')
  if(!hasModule(session.account,'laser-quoting')){location.replace('/app/billing.html?module=laser-quoting')}
  else if(!['owner','admin','manager'].includes(session.role)){message('Quoting is available to owners, admins and managers. Ask your company administrator to update your role.',true)}
  else{
    $('workspace').hidden=false;buildFields();guided=workflow({getState:()=>({imported,current,dirty}),get:apiGet,post:apiPost,run,notice:message,reload:loadQuote});guided.update();installBuilder();$('profileEditor').hidden=!['owner','admin'].includes(session.role)
    run(async()=>{profiles=await apiGet('/api/laser-quotes?action=profiles');renderProfiles();await loadIdentity();await refresh();await drafts.init()})
    refreshCustomerPicker=customerPicker({root:$('customerPicker'),field:form.elements.customer,get:apiGet,post:apiPost,profiles:()=>profiles,changed:()=>{ $('profileCustomer').value='';markDirty() }})
    form.addEventListener('input',markDirty);form.addEventListener('change',visibility)
    $('file').onchange=()=>run(async()=>{if(!drafts.canReplace())throw Error('Restore or discard the saved working draft first.');const file=$('file').files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Choose a file under 2 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Could not read the selected file.'));reader.readAsDataURL(file)});const result=await apiPost('/api/laser-quotes?action=import',{file:base64,name:file.name});imported=result;autofillReport(result.source);markDirty();form.elements.reviewed.checked=false;sourceView();message(result.duplicate?'This report was already imported. Its existing source record has been reused.':'Report imported. Reference and blank sheet price filled from the report. Review highlighted values and complete your rates.')})
    form.onsubmit=e=>{e.preventDefault();run(async()=>{if(!imported)throw Error('Import a Han’s report first.');const result=await apiPost('/api/laser-quotes?action=calculate',{import_id:imported.id,rates:rates()});resultView(result);message(result.complete?'Calculation complete. Review and save your quotation.':'Complete the missing settings listed in the breakdown.',!result.complete)})}
    $('saveQuote').onclick=()=>run(async()=>{if(!drafts.canReplace())throw Error('Restore or discard the saved working draft first.');if(!imported)throw Error('Import a Han’s report first.');if(!guided.reviewed())throw Error('Review and confirm the imported report in step 2 first.');if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));current=await apiPost('/api/laser-quotes?action=save',{import_id:imported.id,request_id:requestId,previous_id:current?.id||null,customer_id:$('profileCustomer').value||null,machine_id:$('profileMachine').value||null,rates:rates(),customer:values.customer,reference:values.reference,terms:values.terms,valid_days:Number(values.valid_days),reviewed:form.elements.reviewed.checked});dirty=false;requestId=crypto.randomUUID();await drafts.clear();resultView(current.result);await refresh();message('Quote revision saved. You can print it or mark it issued.')})
    $('loadProfile').onclick=()=>{const profile=profiles.find(p=>p.id===$('profile').value);if(profile){if(!applyProfile(profile))return;markDirty();message('Profile loaded. Review the applied settings, currency and job-specific costs. Standard: '+profile.name)}}
    $('saveProfile').onclick=()=>run(async()=>{const profile=await apiPost('/api/laser-quotes?action=profiles',{name:$('profileName').value,rates:rates(),profile:{kind:$('profileKind').value,customer_id:$('profileCustomer').value||null,machine_id:$('profileMachine').value||null,customer:form.elements.customer.value,terms:form.elements.terms.value,valid_days:form.elements.valid_days.value}});profiles.push(profile);renderProfiles();$('profile').value=profile.id;message('New profile saved. It is available to this shop on future quotations.')})
    for(const [id,status]of [['issueQuote','issued'],['acceptQuote','accepted'],['declineQuote','declined'],['expireQuote','expired']])$(id).onclick=()=>run(async()=>{if(!current||dirty)throw Error('Save this revision first.');if(!confirm('Record this quotation as '+status+'? This does not send an email.'))return;current=await apiPost('/api/laser-quotes?action=status',{id:current.id,status});resultView(current.result);await refresh();message('Quote marked '+status+'. No email has been sent.')})
    $('quoteList').onclick=e=>{const button=e.target.closest('[data-quote]');if(button)run(async()=>{if(!drafts.canReplace())throw Error('Restore or discard your saved working draft first.');if(dirty&&!confirm('Open this saved quote and discard current working changes?'))return;if(await drafts.clear()){await loadQuote(button.dataset.quote);document.dispatchEvent(new CustomEvent('quote-view',{detail:'builder'}))}})}
    setupIdentity();$('downloadPdf').onclick=()=>run(downloadPdf);
    $('refreshList').onclick=()=>run(refresh);$('printQuote').onclick=printQuote
    $('newQuote').onclick=()=>run(async()=>{if(!drafts.canReplace())throw Error('Restore or discard the saved working draft first.');if((!dirty||confirm('Discard working changes and start a new quote?'))&&await drafts.clear())reset()})
    $('duplicateQuote').onclick=()=>run(async()=>{if(!current||dirty)throw Error('Open a saved revision first.');if(!drafts.canReplace())throw Error('Resolve the working draft first.');current=null;form.elements.reviewed.checked=false;markDirty();await drafts.flush();message('Copied into a new quotation. Review customer, rates and validity, then save to create a new quote number.')})
  }
}

function fieldHelp(key){if(key.startsWith('company_'))return key==='company_name'?'Your company name as it should appear on the quote. Required for PDF generation.':'Optional company contact detail printed on new quote revisions. Save the company profile to reuse it.';if(key.startsWith('user_'))return key==='user_name'?'Your name as the quote preparer. Required for PDF generation.':'Optional professional contact detail printed on new quote revisions. This does not change your sign-in account.';return ({
 file:'Required for a new quotation. Import the Han’s LaserNest workbook; the report supplies part sizes, quantities, sheet size and processing times. No drawings are needed in this version.',
 customer:'The customer receiving this quote. Load a customer profile to reuse its name and commercial defaults.',reference:'Your customer’s purchase enquiry or drawing reference. Initially filled from the report program; you can edit it.',valid_days:'Number of days the quoted price remains valid, from the issue date (or creation date for a draft).',currency:'All monetary entries use this currency. Loading rates does not convert currencies.',
 method:'Shop cost uses your rates. Han’s comparison starts with the report’s configured material, cutting, piercing and travel charges; those are not verified actual costs.',materialMode:'Charge for each full sheet, calculate full-sheet mass at a price per kg, or record customer-supplied material at zero cost.',sheetPrice:'Price of one full stock sheet. Import can suggest the report material charge divided by sheet count; confirm that this is your intended cost and currency.',pricePerKg:'Your supplier price per kilogram of this material, in the selected currency.',density:'Material density in grams per cubic centimetre, used to turn full-sheet dimensions into mass. Confirm it with your material specification.',remnantCredit:'Amount deducted for reusable material. Enter 0 when there is no credit. It cannot exceed material cost.',machineHourly:'Machine processing cost per hour. Exclude any gas, power and labor charged separately to avoid counting them twice.',setupMinutes:'Time for setup on this job. Enter 0 if no separate setup charge applies.',setupHourly:'Hourly setup labor cost. Needed only when setup minutes are above zero.',laborMinutes:'Additional labor outside machine processing and setup, such as sorting. Enter 0 if none.',laborHourly:'Hourly cost for additional labor. Needed only when additional labor minutes are above zero.',
 gasMode:'Choose your supplier’s pack price, price per standard cubic metre, a manual job amount, or document why gas is included elsewhere.',packPrice:'Total refill or bottle-pack price in the quote currency. Use the same pack represented by bottle count and volume.',bottles:'Whole number of bottles covered by the pack price. For a single cylinder, enter 1.',volumePerBottle:'Supplier-stated standard cubic metres of usable gas per bottle before the usable percentage. Do not enter cylinder water capacity in litres.',usablePct:'Percentage of stated gas volume expected to be usable, greater than 0 and at most 100. Enter your supplier or shop assumption.',gasUnitPrice:'Price per standard cubic metre in the quote currency.',gasFlowLmin:'Cutting flow in standard litres per minute. Use a verified process setting appropriate to this machine, gas, material and thickness.',pierceFlowLmin:'Piercing flow in standard litres per minute. Do not assume it equals cutting flow.',purgeSeconds:'Additional gas-on seconds beyond report cutting and piercing, charged at cutting flow. Enter 0 if none.',gasManualCost:'Your total gas cost estimate for the complete job.',gasReason:'Explain where gas is already included, or why it is excluded. A reason is mandatory when no separate gas charge is made.',
 electricityMode:'Estimate from average input power and time, enter a whole-job power cost, or explain where power is included.',powerKw:'Average electrical input for the machine and included auxiliaries. This is not the laser’s optical power rating.',energyPrice:'Your electricity tariff per kilowatt-hour, in the quote currency. Include only charges you intend to recover here.',electricityManualCost:'Your total electricity cost estimate for this job.',electricityReason:'Explain where electricity is already included, or why excluded. A reason is mandatory for this choice.',otherCost:'Additional operations or overhead for the complete job. Enter 0 if none.',pricing:'Margin is a percentage of the final selling price; markup is a percentage added to costs.',percentage:'Your target margin or markup percentage. Zero is allowed. Margin must remain below 100%. This value is excluded from the customer PDF.',minimumCharge:'Lowest batch selling price you will accept. Enter 0 to apply no minimum.',terms:'Optional customer-facing payment terms, lead time and exclusions. These appear on the printed quote.',reviewed:'Required to save: confirm that imported quantities, units, currency, report warnings and included expenses have been checked.',
 profile:'Optional shortcut. Profile types load only their relevant settings. Names show customer and machine associations. Review compatibility before using a standard.',profileKind:'Choose the settings to reuse: customer commercial defaults, machine costs and load, gas supply and process rates, electricity tariff, or complete shop settings.',profileCustomer:'Optional association identifying which customer these standards belong to. Choose a saved customer profile first.',profileMachine:'Optional association identifying the machine these standards belong to. Choose a saved machine profile first.',profileName:'Required only when saving a profile. Use a descriptive name, including gas, material and thickness where relevant.'
 })[key]||'Review this setting before saving the quotation.'}
function decorateFields(){
 document.querySelectorAll('#workspace label').forEach(label=>{
  if(label.querySelector('.help-button'))return
  const control=label.querySelector('input,select,textarea');if(!control)return
  const key=control.name||control.id;control.id ||= 'field-'+key
  const heading=document.createElement('span');heading.className='field-heading'
  for(const node of [...label.childNodes])if(node.nodeType===Node.TEXT_NODE){heading.append(node)}
  const badge=document.createElement('span');badge.className='field-status';heading.append(badge)
  const button=document.createElement('button');button.type='button';button.className='help-button';button.textContent='?';button.setAttribute('aria-label','Help: '+heading.textContent.trim());button.setAttribute('aria-expanded','false')
  const help=document.createElement('span');help.className='field-help';help.id='help-'+key;help.hidden=true;help.textContent=fieldHelp(key);button.setAttribute('aria-controls',help.id);control.setAttribute('aria-describedby',help.id)
  button.onclick=e=>{e.preventDefault();help.hidden=!help.hidden;button.setAttribute('aria-expanded',String(!help.hidden))}
  button.onkeydown=e=>{if(e.key==='Escape'){help.hidden=true;button.setAttribute('aria-expanded','false')}}
  heading.append(button);label.prepend(heading);label.append(help)
 });updateRequirements()
}
function updateRequirements(){
 const r=rates(),optional=['customerSearch','savedCustomer','reference','terms','profile','profileKind','profileCustomer','profileMachine','remnantCredit','setupMinutes','laborMinutes','purgeSeconds','otherCost','minimumCharge']
 document.querySelectorAll('#workspace label').forEach(label=>{const control=label.querySelector('input,select,textarea'),badge=label.querySelector('.field-status');if(!control||!badge)return;const key=control.name||control.id
  let text=optional.includes(key)?'Optional':key==='profileName'?'Required to save profile':key==='file'?'Required for new quote':'Required'
  if(key==='setupHourly')text=+r.setupMinutes>0?'Required':'Optional · no setup'
  if(key==='laborHourly')text=+r.laborMinutes>0?'Required':'Optional · no additional labor'
  if(key==='reviewed')text='Required to save'
  if(key.startsWith('company_')||key.startsWith('user_'))text=key.endsWith('_name')?'Required for PDF':'Optional'
  badge.textContent=text
  // The server returns all missing cost inputs together; avoid browser validation hiding that checklist.
  control.setAttribute('aria-required',String(text.startsWith('Required')))
 })
}
function autofillReport(source){
 const suggest=(key,value)=>{const field=form.elements[key];if(!field.value||field.dataset.origin==='report'){field.value=value;field.dataset.origin='report';const label=field.closest('label');let note=label.querySelector('.autofill-note');if(!note){note=document.createElement('span');note.className='autofill-note';label.append(note)}note.textContent='Filled from report · confirm before saving'}}
 suggest('reference',source.program)
 if(source.sheetCount>0)suggest('sheetPrice',String(Number((source.charges.material/source.sheetCount).toFixed(8))))
}
function renderProfiles(){
 refreshCustomerPicker()
 const describe=p=>{const meta=p.rates._profile||{kind:'shop'};return [meta.kind,p.name,...['customer_id','machine_id'].map(k=>profiles.find(x=>x.id===meta[k])?.name)].filter(Boolean).join(' · ')}
 $('profile').innerHTML='<option value="">Choose a profile</option>'+profiles.map(p=>`<option value="${esc(p.id)}">${esc(describe(p))}</option>`).join('')
 for(const [id,kind,label]of [['profileCustomer','customer','All customers in this shop'],['profileMachine','machine','All machines in this shop']]){const selected=$(id).value;$(id).innerHTML=`<option value="">${label}</option>`+profiles.filter(p=>p.rates._profile?.kind===kind).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$(id).value=selected}
}
function applyProfile(profile){
 const meta=profile.rates._profile||{kind:'shop'}
 const keys={customer:['currency','pricing','percentage','minimumCharge'],machine:['machineHourly','powerKw','setupHourly','laborHourly'],gas:['gasMode','packPrice','bottles','volumePerBottle','usablePct','gasUnitPrice','gasFlowLmin','pierceFlowLmin','purgeSeconds','gasManualCost','gasReason'],electricity:['electricityMode','energyPrice','electricityManualCost','electricityReason']}[meta.kind]
 const values=keys?Object.fromEntries(keys.map(k=>[k,profile.rates[k]])):profile.rates
 if(meta.kind!=='customer'&&profile.rates.currency!==form.elements.currency.value){message('This profile uses '+profile.rates.currency+'. Change the quote currency or select a matching profile; currency conversion is not automatic.',true);return false}
 fill(values)
 if(meta.kind==='customer'){fill({customer:meta.customer,terms:meta.terms,valid_days:meta.valid_days});$('profileCustomer').value=profile.id}
 if(meta.kind==='machine')$('profileMachine').value=profile.id
 for(const key of Object.keys(values)){const field=form.elements[key];if(field){delete field.dataset.origin;field.closest('label')?.querySelector('.autofill-note')?.remove()}}
 return true
}

async function loadIdentity(){
 const identity=await apiGet('/api/laser-quotes?action=identity')
 for(const kind of ['company','user'])for(const [key,value]of Object.entries(identity[kind]||{})){const field=$(kind+'_'+key);if(field)field.value=value}
 $('companyIdentity').querySelectorAll('input,button').forEach(el=>el.disabled=!['owner','admin'].includes(session.role))
}
function setupIdentity(){
 for(const kind of ['company','user'])$(kind+'Identity').onsubmit=e=>{e.preventDefault();run(async()=>{
  const details=Object.fromEntries([...new FormData(e.target)].map(([key,value])=>[key.slice(kind.length+1),value]))
  await apiPost('/api/laser-quotes?action=identity',{kind,details})
  if(imported)markDirty()
  message((kind==='company'?'Company':'User')+' profile saved. Save a new quote revision to include these details in its PDF.')
 })}
}
async function downloadPdf(){
 if(!current||dirty)throw Error('Save the reviewed quote revision first.')
 const data=await apiGet('/api/laser-quotes?action=pdf&id='+encodeURIComponent(current.id))
 const bytes=Uint8Array.from(atob(data.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}))
 const link=document.createElement('a');link.href=url;link.download=data.filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)
 message('One-page PDF created. Your browser will download it; no external software is required.')
}
