
export function workflow({getState,get,post,run,notice,reload}){
 const $=id=>document.getElementById(id);let calculation=null,reviewedSource=null,shownId=null;
 const panel=document.createElement('section');panel.className='panel workflow';panel.innerHTML=`<h2>Your quotation, step by step</h2><nav aria-label="Quotation steps" class="workflow-steps">${['Import','Review report','Price','Preview','Issue & share'].map((s,i)=>`<button type="button" data-step="${i}" aria-label="Step ${i+1}: ${s}"><span>${i+1}</span>${s}</button>`).join('')}</nav><p id="workflowHint" role="status"></p><button type="button" id="workflowNext" class="btn-app">Choose report</button>`;
 $('workspace').prepend(panel);
 const preview=document.createElement('dialog');preview.id='quotePreview';preview.setAttribute('aria-label','Customer quotation preview');preview.innerHTML='<button type="button" class="btn-app btn-app--secondary" id="closePreview">Close preview</button><div id="previewBody"></div>';document.body.append(preview);$('closePreview').onclick=()=>preview.close();
 const share=document.createElement('section');share.id='approvalPanel';share.className='panel';share.hidden=true;share.innerHTML=`<h2>Customer approval</h2><p>Issue and preview the saved revision, then create a private link for your customer. Anyone holding the link can view and respond. Links expire within 30 days or at the quotation expiry, whichever comes first.</p><div class="actions"><button id="createApproval" class="btn-app" type="button">Create / replace approval link</button><button id="revokeApproval" class="btn-app btn-app--secondary" type="button">Revoke links</button><button id="refreshApproval" class="btn-app btn-app--secondary" type="button">Refresh responses</button></div><div id="approvalUrl" hidden><label>Private link — copy and share yourself<input id="approvalLink" readonly></label><button id="copyApproval" class="btn-app btn-app--secondary" type="button">Copy link</button><p>No email has been sent. Replacing or revoking disables older links. Copy this link now; it is not retrievable after leaving this page.</p></div><div id="approvalHistory" aria-live="polite"></div>`;
 $('quoteActions').parentElement.append(share);
 const review=document.createElement('label');review.className='check';review.innerHTML='<input type="checkbox" id="sourceReviewed"> I reviewed the imported parts, quantities, millimetre units and report warnings.';$('parts').after(review);
 review.querySelector('input').onchange=()=>{reviewedSource=$('sourceReviewed').checked?getState().imported?.id:null;update()};
 function jump(id){const e=$(id);e.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});if(e.matches('input,button'))e.focus()}
 function showPreview(){const {current,dirty}=getState();if(!current||dirty){notice('Save a reviewed revision before previewing the customer quotation.',true);return}const q=current,s=q.source,r=q.result,c=r.identity?.company||{};window.renderCustomerQuote({number:'LQ-'+q.family_id.slice(0,8).toUpperCase(),revision:q.revision,customer:q.customer,reference:q.reference,terms:q.terms,status:q.status,issued_at:q.issued_at,valid_until:q.issued_at?new Date(Date.parse(q.issued_at)+q.valid_days*86400000).toISOString():null,price:r.price,currency:r.currency,material:s.material,thickness:s.thicknessMm,company:{name:c.name||'Quotation',address:c.address||'',email:c.email||''},prepared_by:r.identity?.user?.name||'',parts:s.parts.map(p=>({name:p.name,width:p.widthMm,height:p.heightMm,quantity:p.nested}))},$('previewBody'));preview.showModal()}
 const previewButton=document.createElement('button');previewButton.type='button';previewButton.className='btn-app btn-app--secondary';previewButton.id='previewQuote';previewButton.textContent='Preview customer quotation';previewButton.onclick=showPreview;$('quoteActions').prepend(previewButton);
 function go(step){if(step===0)jump('file');if(step===1)jump('sourceReviewed');if(step===2)jump('quoteForm');if(step===3)showPreview();if(step===4){if(!getState().current||getState().dirty){notice('Save a reviewed revision before issuing it.',true);return}jump('quoteActions')}}
 panel.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>go(Number(b.dataset.step)));
 async function history(){const {current}=getState();if(!current)return;const id=current.id;const rows=await get('/api/laser-quotes?action=approval&id='+id);if(getState().current?.id!==id)return;$('approvalHistory').replaceChildren();if(!rows.length){$('approvalHistory').textContent='No approval links created for this revision.';return}for(const row of rows){const card=document.createElement('div');card.className='approval-entry';const title=document.createElement('strong');title.textContent=row.response?row.response.replaceAll('_',' '):row.revoked_at?'Revoked':Date.parse(row.expires_at)<=Date.now()?'Expired':'Awaiting response';card.append(title);const detail=document.createElement('p');detail.textContent=row.response?`${row.responder_name} · ${row.responder_email} · ${new Date(row.responded_at).toLocaleString()}${row.purchase_order?' · PO: '+row.purchase_order:''}`:'Created '+new Date(row.created_at).toLocaleString();card.append(detail);if(row.message){const msg=document.createElement('p');msg.textContent=row.message;card.append(msg)}$('approvalHistory').append(card)}}
 $('createApproval').onclick=()=>run(async()=>{const {current,dirty}=getState();if(!current||dirty)throw Error('Save this revision first.');if(!confirm('Create a private approval link? Existing links for this revision will stop working. No email will be sent.'))return;const data=await post('/api/laser-quotes?action=approval',{id:current.id,operation:'create'});$('approvalLink').value=data.url;$('approvalUrl').hidden=false;await history();notice('Private approval link created. Copy it and share it with your customer.')});
 $('copyApproval').onclick=async()=>{try{await navigator.clipboard.writeText($('approvalLink').value);notice('Approval link copied.')}catch(_){$('approvalLink').focus();$('approvalLink').select();notice('Select and copy the link above.')}};
 $('revokeApproval').onclick=()=>run(async()=>{if(!confirm('Disable all approval links for this revision?'))return;await post('/api/laser-quotes?action=approval',{id:getState().current.id,operation:'revoke'});$('approvalUrl').hidden=true;$('approvalLink').value='';await history();notice('Approval links revoked.')});
 $('refreshApproval').onclick=()=>run(async()=>{await reload(getState().current.id);await history();notice('Quotation and customer responses refreshed.')});
 function update(result){if(result)calculation=result;const {imported,current,dirty}=getState();if(!imported){calculation=null;reviewedSource=null}if($('sourceReviewed'))$('sourceReviewed').checked=!!imported&&reviewedSource===imported.id;
  const saved=!!current&&!dirty;let step=!imported?0:reviewedSource!==imported.id&&!saved?1:!saved?2:current.status==='draft'?3:4;
  panel.querySelectorAll('[data-step]').forEach((b,i)=>{b.classList.toggle('complete',i<step);if(i===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');b.disabled=i>0&&!imported||i>=3&&!saved});
  const hints=['Upload your Han’s report to begin.','Check the extracted parts and warnings, then confirm the report below.',calculation&&!calculation.complete?'Still needed: '+calculation.missing.join('; '):'Enter customer and costing settings, calculate, confirm your review and save a revision.','Your revision is saved. Preview the customer-facing price and terms before issuing.','Issue a draft to enable a customer approval link. Refresh responses to check for acceptance or changes.'];
  $('workflowHint').textContent=hints[step];$('workflowNext').textContent=['Choose report','Review imported report','Go to pricing','Preview quotation','Go to issue & share'][step];$('workflowNext').onclick=()=>go(step);
  share.hidden=!saved;if(saved){$('createApproval').disabled=current.status!=='issued'||Date.now()>=Date.parse(current.issued_at)+current.valid_days*86400000;if(shownId!==current.id){shownId=current.id;$('approvalUrl').hidden=true;$('approvalLink').value='';history().catch(e=>notice(e.message,true))}}else{shownId=null;$('approvalUrl').hidden=true;$('approvalLink').value=''}
 }
 return {update,resetReview(){reviewedSource=null;calculation=null;update()},invalidate(){calculation=null;update()},reviewed(){return !!getState().imported&&reviewedSource===getState().imported.id},restoreReview(){reviewedSource=getState().imported?.id||null;update()}};
}
