const assert=require('assert/strict');const {chromium}=require('playwright');const {start}=require('./laser-browser-server.cjs');
(async()=>{const app=await start();const browser=await chromium.launch({headless:true,...(process.env.BILLET_BROWSER_EXECUTABLE?{executablePath:process.env.BILLET_BROWSER_EXECUTABLE}:{})});try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let checkout=0;
 await page.addInitScript(({account,user})=>{sessionStorage.setItem('axon_access_token','test-token');sessionStorage.setItem('axon_account',JSON.stringify({...account,plan:'trial'}));sessionStorage.setItem('axon_role','owner');sessionStorage.setItem('axon_user',JSON.stringify(user))},{account:app.account,user:app.user});
 await page.route('**/api/billing?action=status',r=>r.fulfill({json:{checkout_ready:true,portal_ready:false,test_mode:true,trial_end:1799366400}}));
 await page.route('**/api/billing?action=checkout',r=>{checkout++;assert.equal(r.request().postDataJSON().accept_recurring,true);return r.fulfill({status:503,json:{error:'Fixture: stop before checkout'}})});
 await page.goto(app.url+'/app/billing.html');await page.getByRole('button',{name:'Choose Starter'}).click();assert.equal(checkout,0);await page.locator('#recurringConsent').check();await page.getByRole('button',{name:'Choose Starter'}).click();await page.getByText('Fixture: stop before checkout',{exact:true}).waitFor();assert.equal(checkout,1);assert.equal(await page.locator('[data-plan="suite"]').count(),0);assert.match(await page.locator('#trialSchedule').innerText(),/first monthly USD charge/);
 for(const route of ['/app/billing.html','/pricing.html','/packages/starter/','/packages/growth/','/packages/suite/']) {await page.goto(app.url+route);for(const width of [390,820,1440]) {await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' overflow '+width)}}
 assert.deepEqual(errors,[]);console.log('Billing consent, Suite restriction, charge-date display and mobile/tablet/desktop pricing passed.');
 }finally{await browser.close();await app.close()}})().catch(e=>{console.error(e);process.exitCode=1});
