const test=require('node:test'),assert=require('node:assert/strict'),vm=require('vm'),fs=require('fs');
const A='10000000-0000-4000-8000-000000000001',M='10000000-0000-4000-8000-000000000002',U='10000000-0000-4000-8000-000000000003';
function setup({role='operator',found=true,ready=false,accepted=true}={}){const calls=[];const source=fs.readFileSync(__dirname+'/../api/_lib/company-users.js','utf8');const sandbox={module:{exports:{}},URL,require:n=>n==='./security'?{...require('../api/_lib/security'),siteUrl:()=> 'https://example.invalid'}:n==='./email'?{emailStatus:()=>({invitations_ready:ready}),invitationEmail:()=>({secure:true}),passwordResetEmail:()=>({secure:true}),sendEmail:async o=>{calls.push(['send',o]);return{ok:accepted}}}:{sb:async(m,p,b)=>{calls.push([m,p,b]);if(p.startsWith('accounts?'))return[{id:A,name:'Fixture'}];if(m==='GET')return found?[{id:M,user_id:U,role,full_name:'Name',email:'member@example.invalid',token:'private',expires_at:'2099-01-01'}]:[];return[{id:M,...b}]},authAdmin:async(m,p,b)=>{calls.push(['auth',m,p,b]);return p==='generate_link'?{action_link:'https://auth.example.invalid/verify?token=private&redirect_to='+encodeURIComponent('https://example.invalid/app/reset-password.html')}:{email:'member@example.invalid'}}}};vm.runInNewContext(source,sandbox);return{...sandbox.module.exports,calls}}
const response=()=>({status(c){this.code=c;return this},json(b){this.body=b;return this}});
function req(resource,method,body={}){return{method,query:{resource,id:M},body:{account_id:A,...body}}}
test('user edits reject membership from another company',async()=>{const h=setup({found:false}),r=response();await h.companyUsers(req('company-user','PATCH',{full_name:'Changed'}),r);assert.equal(r.code,404);assert(!h.calls.some(c=>c[0]==='PATCH'))});
test('membership edits update only the selected company and allowlisted fields',async()=>{const h=setup(),r=response();await h.companyUsers(req('company-user','PATCH',{full_name:'  New Name ',role:'manager',user_id:'attacker',password:'bad'}),r);assert.equal(r.code,200);const write=h.calls.find(c=>c[0]==='PATCH');assert(write[1].includes('account_id=eq.'+A));assert.deepEqual(JSON.parse(JSON.stringify(write[2])),{full_name:'New Name',role:'manager'})});
test('owner removal and demotion remain blocked',async()=>{for(const method of ['DELETE','PATCH']){const h=setup({role:'owner'}),r=response();await h.companyUsers(req('company-user',method,{role:'viewer'}),r);assert.equal(r.code,409);assert(!h.calls.some(c=>['DELETE','PATCH'].includes(c[0])))}});
test('reset without secure sender never generates or sends a token',async()=>{const h=setup(),r=response();await h.companyUsers(req('user-reset','POST'),r);assert.equal(r.code,409);assert(!h.calls.some(c=>c[0]==='auth'||c[0]==='send'))});
test('reset is sent only to the stored user email and never returned to admin',async()=>{const h=setup({ready:true}),r=response();await h.companyUsers(req('user-reset','POST',{email:'attacker@example.invalid'}),r);assert.equal(r.code,200);assert.equal(h.calls.find(c=>c[0]==='send')[1].to,'member@example.invalid');assert(!JSON.stringify(r.body).includes('private'));assert.equal(h.calls.find(c=>c[2]==='generate_link')[3].type,'recovery')});
test('failed email returns failure without pretending it was delivered',async()=>{const h=setup({ready:true,accepted:false}),r=response();await h.companyUsers(req('user-reset','POST'),r);assert.equal(r.code,502)});
test('invitation revocation is scoped to the company',async()=>{const h=setup(),r=response();await h.companyUsers(req('company-invite','DELETE'),r);assert.equal(r.code,200);assert(h.calls.find(c=>c[0]==='DELETE')[1].includes('account_id=eq.'+A))});
