const test=require('node:test'),assert=require('assert/strict'),vm=require('vm'),fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..'),ID='10000000-0000-4000-8000-000000000001';
function setup({allowed=true,exists=false}={}){const calls=[],conversions=[];const sb=async(m,p,b)=>{calls.push({m,p,b});if(p.startsWith('rpc/'))return allowed;if(m==='GET')return exists?[{id:ID}]:[];return[{id:ID}]};const c={module:{exports:{}},process:{env:{CRON_SECRET:'test'}},require:n=>n==='./_lib/supabase'?{sb}:n==='./_lib/security'?require(root+'/api/_lib/security'):n==='./_lib/engagement'?{conversion:async(...x)=>conversions.push(x)}:require(n),Date};vm.runInNewContext(fs.readFileSync(root+'/api/submit-contact.js','utf8').replace('export default async function handler','async function handler')+';this.handler=handler',c);return{...c,calls,conversions}}
const res=()=>({code:200,setHeader(){},status(n){this.code=n;return this},json(b){this.body=b;return this}}),body=()=>({request_id:ID,name:'Test',email:'TEST@example.com',company:'Shop',topic:'ERP',message:'Quote software question',privacy_ack:true});
async function run(f,b=body(),origin='https://getovrendi.com'){const r=res();await f.handler({method:'POST',headers:{origin,'x-vercel-forwarded-for':'192.0.2.1'},body:b},r);return r}
test('contact validates inputs, acknowledgement and origin before saving',async()=>{for(const b of [{...body(),name:{}},{...body(),email:'bad'},{...body(),topic:'forged'},{...body(),privacy_ack:false},{...body(),message:'x'.repeat(6001)}]){const f=setup();assert.equal((await run(f,b)).code,400);assert.equal(f.calls.length,0)}const f=setup();assert.equal((await run(f,body(),'https://evil.example')).code,403)});
test('contact saves only allowed fields and tracks successful contact conversion',async()=>{const f=setup();assert.equal((await run(f,{...body(),staff_notes:'evil',status:'resolved'})).code,200);const row=f.calls.find(c=>c.p==='ovrendi_website_enquiries'&&c.m==='POST').b;assert.equal(row.email,'test@example.com');assert.equal(row.staff_notes,undefined);assert.equal(row.status,undefined);assert(!JSON.stringify(row).includes('192.0.2.1'));assert.equal(f.conversions[0][1],'contact')});
test('contact duplicate retries and bots do not create more CRM records',async()=>{const f=setup({exists:true});assert.equal((await run(f)).code,200);assert.equal(f.calls.filter(c=>c.m==='POST'&&!c.p.startsWith('rpc/')).length,0);assert.equal(f.conversions.length,0);const b=setup();await run(b,{...body(),website:'spam'});assert.equal(b.calls.length,0)});
test('contact rate limit rejects before database insert',async()=>{const f=setup({allowed:false});assert.equal((await run(f)).code,429);assert.equal(f.calls.length,1)});
test('enquiry database permissions and atomic limiter deny public access',async()=>{const {PGlite}=require('@electric-sql/pglite'),db=new PGlite();try{await db.exec("create role anon;create role authenticated;create role service_role;create table ovrendi_event_limits(bucket text primary key,hits int,expires_at timestamptz);create table ovrendi_web_events(form text constraint ovrendi_web_events_form_check check(form in ('','demo','signup')));");await db.exec(fs.readFileSync(root+'/supabase/migrations/20261009183420_website_enquiries.sql','utf8'));for(let i=1;i<=6;i++)assert.equal((await db.query("select ovrendi_contact_allow('test') as ok")).rows[0].ok,i<=5);const p=(await db.query("select has_table_privilege('anon','ovrendi_website_enquiries','SELECT') as read,has_table_privilege('authenticated','ovrendi_website_enquiries','INSERT') as write,has_function_privilege('anon','ovrendi_contact_allow(text)','EXECUTE') as rpc")).rows[0];assert.deepEqual(p,{read:false,write:false,rpc:false});await db.exec("insert into ovrendi_web_events values('contact')")}finally{await db.close()}});
