const test=require('node:test'),assert=require('assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');
const A='10000000-0000-4000-8000-000000000001',U='10000000-0000-4000-8000-000000000002';
function setup(auth=true){const calls=[];const sb=async(m,p,b)=>{calls.push({m,p,b});return p==='rpc/ovrendi_event_allow'?true:m==='POST'?[{id:A,status:'new'}]:[]};const deps={sb,cors(){},requireAuth:async(req,res)=>auth?{user:{id:U},account:{id:A}}:(res.status(401).json({error:'Unauthorized'}),null)};
const helper={module:{exports:{}},require:n=>n==='./supabase'?deps:require(root+'/api/_lib/security'),Date};vm.runInNewContext(fs.readFileSync(root+'/api/_lib/engagement.js','utf8'),helper);
const app={console,Date,process:{env:{CRON_SECRET:'fixture'}},require:n=>n==='./_lib/supabase'?deps:n==='./_lib/engagement'?helper.module.exports:require(n)};vm.runInNewContext(fs.readFileSync(root+'/api/engagement.js','utf8').replace('export default async function handler','async function handler')+';this.handler=handler',app);return{app,calls,helper:helper.module.exports};}
const res=()=>({code:200,setHeader(){},status(n){this.code=n;return this},json(b){this.body=b;return this}});
test('bug reports require sign-in and scope reads and writes to authenticated identity',async()=>{let x=setup(false),r=res();await x.app.handler({method:'GET',query:{action:'bugs'},headers:{}},r);assert.equal(r.code,401);assert.equal(x.calls.length,0);x=setup();r=res();await x.app.handler({method:'POST',query:{action:'bugs'},headers:{},body:{title:'Issue',details:'Steps',account_id:'foreign',user_id:'foreign',page:'/app/modules/laser-quoting/?token=secret'}},r);assert.equal(r.code,201);const b=x.calls.find(c=>c.m==='POST').b;assert.equal(b.account_id,A);assert.equal(b.user_id,U);assert.equal(b.page,'/app/modules/laser-quoting/');r=res();await x.app.handler({method:'GET',query:{action:'bugs'},headers:{}},r);const query=x.calls.at(-1).p;assert(query.includes('account_id=eq.'+A));assert(query.includes('user_id=eq.'+U));assert(!query.includes('staff_notes'));});
test('public clients cannot forge successful conversions or send analytics without consent',async()=>{for(const body of [{kind:'form_success',consent:true,session_id:A},{kind:'page_view',consent:false,session_id:A}]){const x=setup(),r=res();await x.app.handler({method:'POST',query:{action:'event'},headers:{origin:'https://getovrendi.com'},body},r);assert.equal(r.code,400);assert(!x.calls.some(c=>c.p==='ovrendi_web_events'));}});
test('analytics stores only allowlisted fields and anonymous route categories',async()=>{const x=setup(),r=res();await x.app.handler({method:'POST',query:{action:'event'},headers:{origin:'https://getovrendi.com'},body:{consent:true,session_id:A,kind:'page_view',page:'/app/reset-password.html?token=secret',source:'secret@email.com',email:'secret',form:''}},r);assert.equal(r.code,200);const b=x.calls.find(c=>c.p==='ovrendi_web_events').b;assert.equal(b.page,'/app/other');assert.equal(b.source,'direct');assert(!JSON.stringify(b).includes('secret'));});
test('server conversion ignores absent consent and never breaks submission on analytics failure',async()=>{const x=setup();await x.helper.conversion(null,'demo');assert.equal(x.calls.length,0);await x.helper.conversion({consent:true,session_id:A,page:'/contact/'},'demo');assert.equal(x.calls[0].b.kind,'form_success');});
test('staff reporting rejects invalid report identifiers and statuses',async()=>{const x=setup(),r=res();await x.helper.staffEngagement({method:'PATCH',query:{resource:'bugs',id:'bad&id=other'},body:{status:'resolved',staff_notes:''}},r);assert.equal(r.code,400);assert.equal(x.calls.length,0)});
test('database reporting tables deny customer access and aggregate conversions correctly',async()=>{const {PGlite}=require('@electric-sql/pglite');const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,last_sign_in_at timestamptz);create table public.accounts(id uuid primary key);create table public.account_users(account_id uuid,user_id uuid,full_name text);`);await db.exec(fs.readFileSync(root+'/supabase/migrations/20261009171741_engagement_reporting.sql','utf8'));await db.exec(fs.readFileSync(root+'/supabase/migrations/20261009173523_engagement_activity_snapshot.sql','utf8'));await db.exec('grant select on public.account_users to service_role;set role service_role');await db.query('select * from ovrendi_customer_activity()');await db.exec('reset role');const q=await db.query("select has_table_privilege('authenticated','ovrendi_bug_reports','SELECT') as allowed,has_function_privilege('authenticated','ovrendi_customer_activity()','EXECUTE') as rpc");assert.deepEqual(q.rows[0],{allowed:false,rpc:false});await db.query("insert into ovrendi_web_events(session_id,kind,page,form) values($1,'page_view','/',''),($1,'form_start','/','demo'),($1,'form_success','/','demo'),($1,'form_success','/','demo')",[A]);const t=(await db.query('select ovrendi_web_summary() as s')).rows[0].s;assert.equal(t.totals.visits,1);assert.equal(t.totals.converted_visits,1);assert.equal(t.forms[0].successes,1);for(let i=0;i<121;i++){const a=await db.query('select ovrendi_event_allow($1) as allowed',['bucket']);assert.equal(a.rows[0].allowed,i<120)}}finally{await db.close()}});
