const test=require('node:test'), assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
function helper(env={},fetch=async()=>{throw Error('Unexpected send')}){const s={process:{env},console:{error(){}},AbortSignal,fetch,module:{exports:{}},require:()=>({})};vm.runInNewContext(fs.readFileSync(__dirname+'/../api/_lib/email.js','utf8'),s);return s.module.exports}
test('missing sender never sends using shared onboarding identity',async()=>{assert((await helper({RESEND_API_KEY:'test'}).sendEmail({to:'a@example.invalid'})).skipped)});
test('notification uses branded sender, category and deterministic deduplication',async()=>{let sent;const h=helper({RESEND_API_KEY:'test',FROM_EMAIL:'Ovrendi <hello@notifications.example.invalid>'},async(u,o)=>{sent=o;return{ok:true,json:async()=>({id:'message'})}});assert.equal((await h.sendEmail({to:'a@example.invalid',...h.welcomeEmail('<b>shop</b>','https://example.invalid'),idempotencyKey:'welcome-company'})).ok,true);const body=JSON.parse(sent.body);assert.equal(body.from,'Ovrendi <hello@notifications.example.invalid>');assert.equal(body.tags[1].value,'welcome');assert.equal(sent.headers['Idempotency-Key'],'welcome-company');assert(body.text);assert(!body.html.includes('<b>shop</b>'));assert(!body.html.includes('info@ovrendi.com'))});
test('invitation cannot fall back to the tracked notification sender',async()=>{const h=helper({RESEND_API_KEY:'test',FROM_EMAIL:'notifications@example.invalid'});assert((await h.sendEmail({to:'a@example.invalid',...h.invitationEmail('Shop','https://example.invalid/invite')})).skipped)});
test('secure invitation uses auth credentials and escapes the company and link',async()=>{let sent;const h=helper({RESEND_AUTH_API_KEY:'auth-test',AUTH_FROM_EMAIL:'Ovrendi <hello@auth.example.invalid>'},async(u,o)=>{sent=o;return{ok:true,json:async()=>({id:'invite'})}});assert((await h.sendEmail({to:'a@example.invalid',...h.invitationEmail('<script>','https://example.invalid/?a=1&b=2')})).ok);assert.equal(sent.headers.Authorization,'Bearer auth-test');const b=JSON.parse(sent.body);assert(b.html.includes('&lt;script&gt;'));assert(b.html.includes('&amp;b=2'));assert.equal(b.tags[1].value,'invitation')});
test('provider rejection and network error do not report success',async()=>{for(const fetch of [async()=>({ok:false,status:403}),async()=>{throw Error('private provider detail')}])assert.equal((await helper({RESEND_API_KEY:'test',FROM_EMAIL:'test@example.invalid'},fetch).sendEmail({to:'a@example.invalid'})).ok,false)});
function admin({authorized=true,ready=false,accepted=true}={}){const calls=[];const sandbox={console,process:{env:{}},require(name){if(name==='./_lib/security')return{siteUrl:()=> 'https://example.invalid'};if(name==='./_lib/email')return{emailStatus:()=>({notifications_ready:ready,invitations_ready:ready}),welcomeEmail:()=>({}),invitationEmail:()=>({}),sendEmail:async options=>{calls.push(['email',options]);return{ok:accepted}}};return{cors(){},requireAxonAdmin(req,res){if(!authorized)res.status(403).json({error:'Forbidden'});return authorized},sb:async(method,path,body)=>{calls.push([method,path]);return path.startsWith('accounts?')?[{name:'Test'}]:[{id:'invite',token:'private'}]}}}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/../api/axon-admin.js','utf8').replace('export default async function handler','async function handler')+'\nthis.handler=handler',sandbox);return{calls,handler:sandbox.handler}}
const res=()=>({status(n){this.code=n;return this},json(b){this.body=b;return this},setHeader(){}});
test('email status and test sends require internal admin authorization',async()=>{for(const resource of ['email','email-test']){const app=admin({authorized:false}),r=res();await app.handler({method:resource==='email'?'GET':'POST',query:{resource},body:{email:'test@example.invalid'}},r);assert.equal(r.code,403);assert.equal(app.calls.length,0)}});
test('secure invitation setup is checked before any invitation is created',async()=>{const app=admin(),r=res();await app.handler({method:'POST',query:{resource:'invite'},body:{email:'test@example.invalid',account_id:'account',send_email:true}},r);assert.equal(r.code,409);assert.equal(app.calls.length,0)});
test('creating a private invitation link sends no email by default',async()=>{const app=admin(),r=res();await app.handler({method:'POST',query:{resource:'invite'},body:{email:'test@example.invalid',account_id:'account'}},r);assert.equal(r.code,201);assert.equal(r.body.email_status,'not_requested');assert(!app.calls.some(c=>c[0]==='email'))});
test('provider failure preserves invitation link and reports failed delivery',async()=>{const app=admin({ready:true,accepted:false}),r=res();await app.handler({method:'POST',query:{resource:'invite'},body:{email:'test@example.invalid',account_id:'account',send_email:true}},r);assert.equal(r.code,201);assert.equal(r.body.email_status,'failed');assert(r.body.invite_url)});

test('auth emails reuse existing key while retaining the separate auth sender',async()=>{let sent;const h=helper({RESEND_API_KEY:'shared-test',AUTH_FROM_EMAIL:'Ovrendi <no-reply@auth.example.invalid>',FROM_EMAIL:'hello@notifications.example.invalid'},async(u,o)=>{sent=o;return{ok:true,json:async()=>({id:'message'})}});assert.equal(h.emailStatus().invitations_ready,true);assert((await h.sendEmail({to:'a@example.invalid',...h.passwordResetEmail('https://example.invalid/reset')})).ok);assert.equal(sent.headers.Authorization,'Bearer shared-test');assert.equal(JSON.parse(sent.body).from,'Ovrendi <no-reply@auth.example.invalid>')});
