const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const U='10000000-0000-4000-8000-000000000001', S='10000000-0000-4000-8000-000000000002';
const token='header.'+Buffer.from(JSON.stringify({session_id:S})).toString('base64url')+'.sig';
function response(){return{status(c){this.code=c;return this},json(b){this.body=b;return this},setHeader(){}}}
function helper({verified=true,confirmed=true,active=true}={}){let calls=[];const sandbox={module:{exports:{}},Buffer,console,process:{env:{SUPABASE_URL:'https://fixture.invalid',SUPABASE_SERVICE_ROLE_KEY:'test',ADMIN_SECRET:'old-key'}},require:n=>n==='./security'?require('../api/_lib/security'):require(n),fetch:async(url,opts)=>{calls.push(url);if(url.endsWith('/user'))return{ok:verified,json:async()=>({id:U,email_confirmed_at:confirmed?'2026-10-01':null})};return{ok:true,text:async()=>JSON.stringify(active)}}};vm.runInNewContext(fs.readFileSync(__dirname+'/../api/_lib/supabase.js','utf8'),sandbox);return{...sandbox.module.exports,calls}}
test('internal APIs reject the retired shared admin key',async()=>{const h=helper(),r=response();assert.equal(await h.requireAxonAdmin({headers:{'x-admin-secret':'old-key'}},r),null);assert.equal(r.code,401);assert.equal(h.calls.length,0)});
test('invalid or unconfirmed identities cannot reach staff lookup',async()=>{for(const options of [{verified:false},{confirmed:false}]){const h=helper(options),r=response();assert.equal(await h.requireAxonAdmin({headers:{authorization:'Bearer '+token}},r),null);assert.equal(r.code,401);assert.equal(h.calls.length,1)}});
test('customer identities and revoked staff sessions are denied',async()=>{const h=helper({active:false}),r=response();assert.equal(await h.requireAxonAdmin({headers:{authorization:'Bearer '+token}},r),null);assert.equal(r.code,403)});
test('approved staff with a live Auth session can access the CRM',async()=>{const h=helper(),r=response();assert.equal((await h.requireAxonAdmin({headers:{authorization:'Bearer '+token}},r)).id,U);assert(h.calls[1].endsWith('rpc/ovrendi_internal_session_valid'))});
function setup({record=true,existing=false,expired=false}={}){let calls=[];const sandbox={module:{exports:{}},require:n=>n==='./security'?require('../api/_lib/security'):n==='crypto'?require('crypto'):{sb:async(method,path,body)=>{calls.push({method,path,body});return method==='GET'?(record?[{id:U,email:'staff@example.invalid',setup_expires_at:expired?'2020-01-01':'2099-01-01'}]:[]):[{id:U}]},authAdmin:async(method,path,body)=>{calls.push({method,path,body});if(existing)throw Error('Duplicate identity');return{id:S}}},console};vm.runInNewContext(fs.readFileSync(__dirname+'/../api/_lib/staff-setup.js','utf8'),sandbox);return{...sandbox.module.exports,calls}}
const body={email:'staff@example.invalid',password:'long-test-password',token:'b'.repeat(64)};
test('used, expired, invalid and wrong-email setup links never create users',async()=>{for(const [options,change] of [[{record:false},{}],[{expired:true},{}],[{}, {email:'other@example.invalid'}],[{}, {token:'invalid'}]]){const h=setup(options),r=response();await h.setupStaff({body:{...body,...change}},r);assert([400,410].includes(r.code));assert(!h.calls.some(c=>c.path==='users'))}});
test('setup does not reset or take over an existing identity',async()=>{const h=setup({existing:true}),r=response();await h.setupStaff({body},r);assert.equal(r.code,409);assert(!h.calls.some(c=>c.method==='PATCH'))});
test('successful setup binds the new identity and consumes its token',async()=>{const h=setup(),r=response();await h.setupStaff({body},r);assert.equal(r.code,200);const patch=h.calls.find(c=>c.method==='PATCH');assert.equal(patch.body.user_id,S);assert.equal(patch.body.setup_token_hash,null);assert(!h.calls[0].path.includes(body.token));assert.equal(r.body.password,undefined)});
