const assert=require('assert/strict'),{chromium}=require('playwright'),{start}=require('./laser-browser-server.cjs'),{sample,rates}=require('./laser-fixture.cjs');
(async()=>{const app=await start(),browser=await chromium.launch({headless:true,executablePath:process.env.BILLET_BROWSER_EXECUTABLE});try{
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://fonts.gstatic.com/**',r=>r.abort());await context.route('**/api/engagement**',r=>r.fulfill({json:{ok:true}}));
 await context.addInitScript(({account,user})=>{sessionStorage.setItem('axon_access_token','test-token');sessionStorage.setItem('axon_account',JSON.stringify(account));sessionStorage.setItem('axon_role','owner');sessionStorage.setItem('axon_user',JSON.stringify(user));localStorage.setItem('ovrendi_analytics_consent','declined');localStorage.setItem(`ovrendi:walkthrough:quoting:${account.id}:${user.id}`,'seen')},{account:app.account,user:app.user});
 const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(app.url+'/app/modules/laser-quoting/');await p.getByText('Working draft autosave is ready.').waitFor();
 await p.locator('[name=customer]').fill('Recovered customer');await p.waitForFunction(()=>document.getElementById('draftStatus').textContent.startsWith('Working draft saved'));
 await p.reload();await p.getByRole('button',{name:'Restore working draft'}).click();assert.equal(await p.locator('[name=customer]').inputValue(),'Recovered customer');assert.equal(await p.locator('[name=reviewed]').isChecked(),false);
 await p.locator('#file').setInputFiles({name:'sample.xls',mimeType:'application/vnd.ms-excel',buffer:sample()});await p.waitForFunction(()=>document.getElementById('sourceSummary').textContent.includes('parts'));
 await p.evaluate(values=>{for(const [k,v] of Object.entries(values)){const e=document.querySelector('[name="'+k+'"]');if(e)e.value=v}document.querySelector('[name=customer]').dispatchEvent(new Event('input',{bubbles:true}))},rates());
 await p.locator('[name=reviewed]').check();await p.getByRole('button',{name:'Save revision',exact:true}).click();await p.getByText('Quote revision saved.',{exact:false}).waitFor();
 await p.getByRole('button',{name:'Duplicate as new quote'}).click();await p.getByText('Copied into a new quotation.',{exact:false}).waitFor();await p.locator('[name=customer]').fill('Duplicated customer');await p.locator('[name=reviewed]').check();await p.getByRole('button',{name:'Save revision',exact:true}).click();await p.getByText('Quote revision saved.',{exact:false}).waitFor();
 assert.equal(await p.locator('#quoteList tbody tr').count(),2);
 await p.getByRole('button',{name:'Mark issued',exact:true}).click();await p.getByText('Quote marked issued. No email has been sent.').waitFor();await p.getByRole('button',{name:'Record declined'}).click();await p.getByText('Quote marked declined. No email has been sent.').waitFor();
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Quoting mobile overflow');
 for(const size of [{width:390,height:844},{width:820,height:1180},{width:1440,height:900}]){await p.setViewportSize(size);await p.goto(app.url+'/index.html');await p.getByRole('link',{name:'Skip to main content'}).focus();assert(await p.getByRole('link',{name:'Skip to main content'}).isVisible());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Homepage overflow '+size.width);assert.equal(await p.locator('.ov-first-visit').count(),0);await p.goto(app.url+'/app/signup.html');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Signup overflow '+size.width)}
 assert.deepEqual(errors,[]);console.log('Browser passed: cloud draft restore, reviewed revisions, duplication, issued/declined workflow, phone/iPad/desktop layouts, reduced motion and keyboard skip link.');
 }finally{await browser.close();await app.close()}})().catch(e=>{console.error(e);process.exitCode=1});
