const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(env={},failure=false){const calls=[];const box={module:{exports:{}},process:{env:{ZOHO_CLIENT_ID:'client-secret-id',ZOHO_CLIENT_SECRET:'private-secret',ZOHO_REFRESH_TOKEN:'private-refresh',ZOHO_MAIL_ACCOUNT_ID:'123',...env}},URLSearchParams,AbortSignal,Date,fetch:async(url,opts)=>{calls.push({url,opts});if(failure)throw Error('private-secret');return{ok:true,json:async()=>url.includes('/oauth/')?{access_token:'private-access',expires_in:3600}:{status:{code:200},data:{messageId:'789'}}}}};vm.runInNewContext(fs.readFileSync(__dirname+'/../api/_lib/zoho-mail.js','utf8'),box);return{...box.module.exports,calls}}
async function run(h,action,method='GET',body,query={}){const res={status(n){this.code=n;return this},json(v){this.body=v;return this}};await h.zohoMail({query:{action,...query},method,body},res);return res}
const message={to:'recipient@example.com',subject:'Test',content:'Draft only'};
test('status exposes configuration names but never tokens',async()=>{const h=setup();const r=await run(h,'status');assert.equal(r.body.configured,true);assert(!JSON.stringify(r.body).includes('private'));assert.equal(h.calls.length,0)});
test('missing credentials fail closed without provider requests',async()=>{const h=setup({ZOHO_REFRESH_TOKEN:''});assert.equal((await run(h,'folders')).code,409);assert.equal(h.calls.length,0)});
test('draft explicitly sets draft mode and pins sender and text format',async()=>{const h=setup();assert.equal((await run(h,'draft','POST',{...message,fromAddress:'attacker@example.com',mode:'send'})).code,200);const b=JSON.parse(h.calls[1].opts.body);assert.equal(b.mode,'draft');assert.equal(b.fromAddress,'hello@getovrendi.com');assert.equal(b.mailFormat,'plaintext');assert.equal(b.askReceipt,'no')});
test('send requires explicit review flag and validates recipients first',async()=>{for(const b of [message,{...message,confirmSend:true,to:'good@example.com\r\nBcc: bad@example.com'},{...message,confirmSend:true,subject:'bad\nheader'}]){const h=setup();assert.equal((await run(h,'send','POST',b)).code,400);assert.equal(h.calls.length,0)}});
test('reviewed send makes one POST with no draft mode and caches token',async()=>{const h=setup();await run(h,'folders');const r=await run(h,'send','POST',{...message,confirmSend:true});assert.equal(r.code,200);assert.equal(h.calls.filter(c=>c.url.includes('/oauth/')).length,1);const writes=h.calls.filter(c=>c.url.endsWith('/messages'));assert.equal(writes.length,1);assert.equal(JSON.parse(writes[0].opts.body).mode,undefined)});
test('message paths reject traversal and caller-selected accounts',async()=>{const h=setup();assert.equal((await run(h,'message','GET',null,{folder:'../accounts',message:'123'})).code,400);assert.equal(h.calls.length,0);await run(h,'message','GET',null,{folder:'456',message:'789',account:'999'});assert(h.calls[1].url.includes('/accounts/123/folders/456/messages/789/content'))});
test('ambiguous provider failure does not retry sends or leak secrets',async()=>{const h=setup({},true);const r=await run(h,'send','POST',{...message,confirmSend:true});assert.equal(r.code,502);assert(!JSON.stringify(r.body).includes('private'));assert.match(r.body.error,/before retrying/);assert.equal(h.calls.length,1)});
test('mailbox resource remains behind staff session guard',async()=>{let reached=false;const code=fs.readFileSync(__dirname+'/../api/axon-admin.js','utf8').replace('export default async function handler','module.exports=async function handler');const box={module:{exports:{}},require:n=>n==='./_lib/supabase'?{cors(){},requireAxonAdmin:async(req,res)=>{res.status(403).json({error:'Forbidden'});return null}}:n==='./_lib/zoho-mail'?{zohoMail(){reached=true}}:{},console};vm.runInNewContext(code,box);const res={status(n){this.code=n;return this},json(){},setHeader(){}};await box.module.exports({method:'GET',query:{resource:'mailbox'}},res);assert.equal(res.code,403);assert.equal(reached,false)});
