import {requireAuth} from './_shared/auth.js';import {renderNav} from './_shared/nav.js';import {apiGet,apiPost} from './_shared/api.js';import {prepareScreenshot} from './_shared/support-image.js';
if(!requireAuth())throw Error('Not authenticated');renderNav('/app/support');
const list=document.getElementById('reports'),result=document.getElementById('result');
function node(tag,text){const e=document.createElement(tag);if(text)e.textContent=text;return e}
async function thread(el,id){el.textContent='Loading conversation…';try{const messages=await apiGet('/api/engagement?action=support&id='+id);el.replaceChildren();for(const m of messages){const p=node('article');p.append(node('strong',(m.sender==='staff'?'Ovrendi support':'You')+' · '+new Date(m.created_at).toLocaleString()),node('pre',m.body));if(m.has_screenshot){const show=node('button','View screenshot');show.type='button';show.onclick=async()=>{show.disabled=true;try{const data=await apiGet('/api/engagement?action=support&id='+id+'&attachment='+m.id);const img=node('img');img.src=data.screenshot;img.alt='Attached support screenshot';img.style.maxWidth='100%';p.append(img);show.remove()}catch(e){show.textContent=e.message;show.disabled=false}};p.append(show)}el.append(p)}
 const f=node('form');f.innerHTML='<label>Your reply · required<textarea name="body" maxlength="6000" required rows="3"></textarea></label><label>Screenshot · optional<input name="screenshot" type="file" accept="image/png,image/jpeg,image/webp"></label><p>Crop or redact private information before attaching a screenshot.</p><button class="btn-app">Send reply</button><p role="status"></p>';
 let request=crypto.randomUUID();f.onsubmit=async e=>{e.preventDefault();const button=f.querySelector('button'),status=f.querySelector('[role="status"]');button.disabled=true;try{const screenshot=await prepareScreenshot(f.elements.screenshot.files[0]);await apiPost('/api/engagement?action=support&id='+id,{body:f.elements.body.value,screenshot,request_id:request});request=crypto.randomUUID();await thread(el,id)}catch(err){status.textContent=err.message;button.disabled=false}};el.append(f);
 }catch(err){el.textContent=err.message}}
async function load(){try{const rows=await apiGet('/api/engagement?action=bugs');list.replaceChildren();if(!rows.length)list.textContent='No reports yet.';for(const row of rows){const el=node('article'),title=node('h3',row.title+' — '+row.status),detail=node('pre',new Date(row.created_at).toLocaleString()+' · '+row.details),button=node('button','View conversation / add screenshot'),conversation=node('div');button.type='button';button.className='btn-app btn-app--secondary';button.onclick=()=>thread(conversation,row.id);el.append(title,detail,button,conversation);list.append(el)}}catch(_){list.textContent='Reports could not be loaded. Refresh to retry.'}}
document.getElementById('bugForm').onsubmit=async e=>{e.preventDefault();const button=document.getElementById('sendReport');button.disabled=true;try{const data=await apiPost('/api/engagement?action=bugs',Object.fromEntries(new FormData(e.target)));result.textContent='Report received. Reference: '+data.id+'. Open its conversation below to add a screenshot or reply.';e.target.reset();await load()}catch(err){result.textContent=err.message}finally{button.disabled=false}};load();
