(() => {
'use strict';
const API='https://axon-ai-website-three.vercel.app/api/axon-admin';
const names={overview:'Overview',accounts:'Companies',contacts:'Contacts',workflows:'Onboarding',tasks:'Tasks & planning',modules:'Module access',activity:'Activity',guide:'Getting customers started'};
const modules=[['production-board','Production Board','Live'],['job-costing','Job Costing + Quoting','Live · Quoting pilot'],['shop-traveler','Shop Traveler','Live'],['customer-portal','Customer Portal','In development'],['maintenance','Maintenance','In development'],['materials','Material Inventory','In development'],['coc','CoC Generator','In development'],['crm','Shop CRM','In development'],['outside-service','Outside Services','In development']];
const limits={starter:1,growth:3,suite:9,trial:9},stages=['discovery','setup','invited','training','pilot','live'];
const $=id=>document.getElementById(id),escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let secret='',data={},view='overview',editing=null,loading=false;
async function api(resource,method='GET',body,id){const res=await fetch(API+'?resource='+resource+(id?'&id='+encodeURIComponent(id):''),{method,headers:{'X-Admin-Secret':secret,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await res.json();if(!res.ok)throw Error(result.error||'Request failed');return result}
function company(id){return data.accounts?.find(a=>a.id===id)?.name||'Unassigned'}
function table(head,rows){return '<div class="table-wrap"><table><thead><tr>'+head.map(x=>'<th>'+escape(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>'}
const editButton=(resource,id,label='Edit')=>`<button data-edit="${resource}" data-id="${escape(id)}" class="secondary">${label}</button>`;
async function load(){if(loading)return;loading=true;$('refresh').disabled=true;try{const resources=['accounts','contacts','tasks','workflows','activity'];const values=await Promise.all(resources.map(r=>api(r)));data=Object.fromEntries(resources.map((r,i)=>[r,values[i]]));render()}finally{loading=false;$('refresh').disabled=false}}
function render(){view=location.hash.slice(1);if(!names[view])view='overview';$('title').textContent=names[view];$('navigation').innerHTML=Object.entries(names).map(([key,label])=>`<a href="#${key}" class="${key===view?'active':''}" ${key===view?'aria-current="page"':''}>${label}</a>`).join('');let h='';
if(view==='overview')h=`<div class="cards"><article class="card"><h3>Companies</h3><strong>${data.accounts.length}</strong></article><article class="card"><h3>Open tasks</h3><strong>${data.tasks.filter(t=>t.status!=='done').length}</strong></article><article class="card"><h3>In onboarding</h3><strong>${data.workflows.filter(w=>w.stage!=='live').length}</strong></article></div><div class="panel"><h2>From first conversation to first quote.</h2><p>Keep commercial plans, software access and onboarding progress in one workspace.</p><a href="#guide">View the customer setup workflow →</a></div><div class="panel"><h3>Next actions</h3>${data.tasks.filter(t=>t.status!=='done').slice(0,8).map(t=>`<p><strong>${escape(t.title)}</strong> · ${escape(company(t.account_id))} · ${escape(t.due_date||'No due date')}</p>`).join('')||'<p>No open tasks. Add the next action for your first customer.</p>'}</div>`;
if(view==='accounts'||view==='modules'){h=`<div class="toolbar"><p>Starter: 1 · Growth: 3 · Suite/trial: up to 9. Quoting uses Job Costing access.</p><button data-edit="accounts">New company</button></div>`;h+=table(['Company','Plan / status','Module access','Actions'],data.accounts.map(a=>`<tr><td>${escape(a.name)}</td><td>${escape(a.plan)}<small>${escape(a.status)}</small></td><td>${a.modules.length} enabled<small>${a.modules.map(m=>escape(modules.find(x=>x[0]===m)?.[1]||m)).join(', ')}</small></td><td>${editButton('accounts',a.id,'Manage access')} ${editButton('invite',a.id,'Invite user')}</td></tr>`))}
if(view==='contacts'){h='<div class="toolbar"><p>Contact records do not grant software access.</p><button data-edit="contacts">Add contact</button></div>';h+=table(['Contact','Company','Email / phone','Actions'],data.contacts.map(c=>`<tr><td>${escape(c.name)}</td><td>${escape(company(c.account_id))}</td><td>${escape(c.email)}<small>${escape(c.phone)}</small></td><td>${editButton('contacts',c.id)}</td></tr>`))}
if(view==='tasks'){h='<div class="toolbar"><p>Plan work, assign a responsible person and track blockers.</p><button data-edit="tasks">Add task</button></div>';h+=table(['Task','Company','Owner / due','Status','Actions'],data.tasks.map(t=>`<tr><td>${escape(t.title)}</td><td>${escape(company(t.account_id))}</td><td>${escape(t.owner_name)}<small>${escape(t.due_date||'No due date')}</small></td><td>${escape(t.status)}</td><td>${editButton('tasks',t.id)}</td></tr>`))}
if(view==='workflows'){h='<div class="toolbar"><p>Move customers through setup with an explicit next step.</p><button data-edit="workflows">Start onboarding</button></div><div class="board">'+stages.map(stage=>`<section class="lane"><h3>${stage}</h3>${data.workflows.filter(w=>w.stage===stage).map(w=>`<div class="workflow"><strong>${escape(company(w.account_id))}</strong><p>${escape(w.next_step||'Set the next step')}</p><small>${escape(w.owner_name)} · ${escape(w.target_date||'No target date')}</small>${editButton('workflows',w.id,'Update stage')}</div>`).join('')||'<small>No companies in this stage.</small>'}</section>`).join('')+'</div>'}
if(view==='activity')h='<p>Recent database changes. This initial history records what changed and when; named staff attribution will follow individual staff login.</p>'+table(['When','Company','Record','Action'],data.activity.map(a=>`<tr><td>${escape(new Date(a.created_at).toLocaleString())}</td><td>${escape(company(a.account_id))}</td><td>${escape(a.resource)}</td><td>${escape(a.action)}</td></tr>`));
if(view==='guide')h='<div class="panel"><h2>Edward’s setup checklist</h2><p>Waiting for Edward’s email, company, role and starting modules. No invitation has been sent.</p><ol class="steps"><li>Create or select the company. Avoid duplicating an existing Antech workspace.</li><li>Select the plan and allowed modules. Start a 14-day trial when appropriate.</li><li>Add Edward as a contact, then create a software invitation with his confirmed email and role.</li><li>Copy the invitation link and share it securely. Email delivery is not configured yet.</li><li>Start onboarding in Setup. Assign an owner and a training target date.</li><li>Configure company details, machine profile, materials, gas and electricity rates.</li><li>Import a sample Han’s export, check the calculation and save the first quotation/PDF.</li><li>Run a reviewed pilot, resolve blockers, then move the workflow to Live.</li></ol></div><div class="panel"><h3>Architecture</h3><p>This separate staff interface uses the existing protected admin API and Supabase company records. Internal contacts, tasks and workflows are private server-only tables. Customer roles do not grant internal access.</p><p>Plan changes here do not charge a card. Paid Stripe plan changes must go through billing. Module limits are enforced by the server.</p></div>';
$('content').innerHTML=h;}
function input(name,label,value='',type='text',required=false){return `<label>${label}${required?' *':' (optional)'}<input name="${name}" type="${type}" value="${escape(value)}" ${required?'required':''} maxlength="${name==='title'?200:120}"></label>`}
function select(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${escape(v)}" ${v===value?'selected':''}>${escape(l)}</option>`).join('')}</select></label>`}
function open(resource,id){const record=resource==='invite'?data.accounts.find(x=>x.id===id):data[resource]?.find(x=>x.id===id)||{};editing={resource,id};$('editTitle').textContent=resource==='invite'?'Create invitation':(id?'Edit ':'Create ')+(resource==='accounts'?'company':resource.slice(0,-1));$('formError').textContent='';let f='';
if(resource==='accounts'){f=input('name','Company name',record.name,'text',true)+select('plan','Plan',Object.keys(limits).map(p=>[p,p]),record.plan||'trial')+select('status','Account status',['active','suspended','cancelled'].map(p=>[p,p]),record.status||'active')+'<p>Select modules within the plan limit. Quoting is included with Job Costing.</p>'+modules.map(([m,label,status])=>`<label class="module-option"><input type="checkbox" name="modules" value="${m}" ${(record.modules||[]).includes(m)?'checked':''}><span>${label}<small>${status}</small></span></label>`).join('')}
else if(resource==='invite'){f=`<p>Invite a user to <strong>${escape(record.name)}</strong>. This creates a private link; it does not send an email.</p>`+input('email','Email address','','email',true)+select('role','Software role',['owner','admin','manager','operator','viewer'].map(r=>[r,r]),'owner')}
else{f=select('account_id','Company',...(resource==='workflows'?[[...data.accounts.map(a=>[a.id,a.name])],record.account_id]:[[['','Unassigned'],...data.accounts.map(a=>[a.id,a.name])],record.account_id||'']));if(resource==='contacts')f+=input('name','Name',record.name,'text',true)+input('email','Email',record.email,'email')+input('phone','Phone',record.phone);if(resource==='tasks')f+=input('title','Task',record.title,'text',true)+select('status','Status',['todo','doing','blocked','done'].map(s=>[s,s]),record.status||'todo')+input('owner_name','Responsible person',record.owner_name)+input('due_date','Due date',record.due_date,'date');if(resource==='workflows')f+=select('stage','Stage',stages.map(s=>[s,s]),record.stage||'setup')+input('owner_name','Responsible person',record.owner_name)+input('next_step','Next step',record.next_step)+input('target_date','Target date',record.target_date,'date');}
if(resource!=='invite'&&resource!=='workflows')f+=`<label>Notes (optional)<textarea name="notes" maxlength="4000">${escape(record.notes)}</textarea></label>`;$('fields').innerHTML=f;$('editor').showModal();}
$('content').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)open(b.dataset.edit,b.dataset.id)});
$('close').onclick=()=>$('editor').close();$('editForm').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;$('formError').textContent='';try{const fd=new FormData(e.target),body=Object.fromEntries(fd);if(editing.resource==='accounts'){body.modules=fd.getAll('modules');if(body.modules.length>limits[body.plan])throw Error('Too many modules for this plan.');}if(editing.resource==='invite')body.account_id=editing.id;for(const key of ['account_id','due_date','target_date'])if(body[key]==='')body[key]=null;const result=await api(editing.resource,editing.id&&editing.resource!=='invite'?'PATCH':'POST',body,editing.resource!=='invite'?editing.id:null);$('editor').close();$('notice').textContent='Saved.';if(editing.resource==='invite'){$('notice').innerHTML='<strong>Invitation created. Copy this private link and share it securely:</strong><p class="invite-result"></p>';$('notice').querySelector('p').textContent=result.invite_url;}await load()}catch(err){$('formError').textContent=err.message}finally{$('save').disabled=false}};
$('login').onsubmit=async e=>{e.preventDefault();secret=$('credential').value;try{await load();$('credential').value='';$('gate').hidden=true;$('workspace').hidden=false}catch(err){secret='';$('loginError').textContent=err.message}};
$('refresh').onclick=()=>load().catch(e=>$('notice').textContent=e.message);$('logout').onclick=()=>{secret='';data={};$('content').textContent='';$('notice').textContent='';$('workspace').hidden=true;$('gate').hidden=false};$('theme').onclick=()=>document.body.classList.toggle('dark');window.addEventListener('hashchange',()=>{if(secret)render()});
})();
