(() => {
'use strict';
const API='https://axon-ai-website-three.vercel.app/api/axon-admin';
const names={overview:'Overview',accounts:'Companies',users:'Company users',contacts:'Contacts',workflows:'Onboarding',tasks:'Tasks & planning',modules:'Module access',activity:'Activity',emails:'Email delivery',guide:'Getting customers started'};
const modules=[['production-board','Production Board','Live'],['job-costing','Job Costing + Quoting','Live · Quoting pilot'],['shop-traveler','Shop Traveler','Live'],['customer-portal','Customer Portal','In development'],['maintenance','Maintenance','In development'],['materials','Material Inventory','In development'],['coc','CoC Generator','In development'],['crm','Shop CRM','In development'],['outside-service','Outside Services','In development']];
const limits={starter:1,growth:3,suite:9,trial:9},stages=['discovery','setup','invited','training','pilot','live'];
const $=id=>document.getElementById(id),escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sessionVersion=0,secret='',refreshToken='',refreshing=null,data={},view='overview',editing=null,loading=false,selectedCompany='',team=null;
async function authRequest(path,body,token) {
 const res=await fetch(SUPABASE_URL+'/auth/v1/'+path,{method:'POST',headers:{apikey:SUPABASE_ANON,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});
 const result=await res.json().catch(()=>({}));if(!res.ok)throw Error(res.status===429?'Too many attempts. Please wait and try again.':'Sign-in failed. Check your email and password.');return result;
}
function clearSession(message='') {sessionVersion++;secret='';refreshToken='';data={};team=null;selectedCompany='';$('content').textContent='';$('notice').textContent='';$('signedInEmail').textContent='';$('workspace').hidden=true;$('gate').hidden=false;$('loginError').textContent=message;if($('editor').open)$('editor').close();}
async function refreshSession() {
 const version=sessionVersion;
 if(!refreshing)refreshing=authRequest('token?grant_type=refresh_token',{refresh_token:refreshToken}).then(s=>{if(version!==sessionVersion)throw Error('Session ended');secret=s.access_token;refreshToken=s.refresh_token;}).finally(()=>refreshing=null);
 return refreshing;
}
async function api(resource,method='GET',body,id,retried=false){
 const res=await fetch(API+'?resource='+resource+(id?'&id='+encodeURIComponent(id):''),{method,headers:{Authorization:'Bearer '+secret,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 const result=await res.json();
 if(res.status===401&&!retried&&refreshToken){try{await refreshSession();return await api(resource,method,body,id,true)}catch(_){clearSession('Your session ended. Please sign in again.');throw Error('Please sign in again.')}}
 if(!res.ok){if(res.status===401||res.status===403)clearSession(result.error);throw Error(result.error||'Request failed')}return result;
}
function company(id){return data.accounts?.find(a=>a.id===id)?.name||'Unassigned'}
function table(head,rows){return '<div class="table-wrap"><table><thead><tr>'+head.map(x=>'<th>'+escape(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>'}
const editButton=(resource,id,label='Edit')=>`<button data-edit="${resource}" data-id="${escape(id)}" class="secondary">${label}</button>`;
async function load(){if(loading)return;loading=true;$('refresh').disabled=true;try{const resources=['accounts','contacts','tasks','workflows','activity'];const values=await Promise.all(resources.map(r=>api(r)));data=Object.fromEntries(resources.map((r,i)=>[r,values[i]]));render()}finally{loading=false;$('refresh').disabled=false}}
async function loadTeam(accountId){selectedCompany=accountId;team=null;render();if(!accountId)return;try{const result=await api('company-team&account_id='+encodeURIComponent(accountId));if(selectedCompany===accountId){team=result;render()}}catch(err){$('notice').textContent=err.message}}
function render(){view=location.hash.slice(1);if(!names[view])view='overview';$('title').textContent=names[view];$('navigation').innerHTML=Object.entries(names).map(([key,label])=>`<a href="#${key}" class="${key===view?'active':''}" ${key===view?'aria-current="page"':''}>${label}</a>`).join('');let h='';
if(view==='users'){
 h='<div class="toolbar"><label>Company<select id="teamCompany"><option value="">Select a company</option>'+data.accounts.map(a=>`<option value="${escape(a.id)}" ${selectedCompany===a.id?'selected':''}>${escape(a.name)}</option>`).join('')+'</select></label>'+(selectedCompany?editButton('invite',selectedCompany,'Invite user'):'')+'</div>';
 if(team){h+=`<p>Manage company membership and names. Removing access does not delete the person’s login or access to other companies.</p>${!team.email_ready?'<div class="panel"><strong>Secure email setup required</strong><p>Invitation links work now. Email delivery and password resets require the untracked auth sender.</p></div>':''}`;
 h+=table(['User','Email','Role','Actions'],team.users.map(u=>`<tr><td>${escape(u.full_name||'Name not set')}</td><td>${escape(u.email)}</td><td>${escape(u.role)}</td><td>${editButton('company-user',u.id,'Edit user')}<button class="secondary" data-team-action="reset" data-id="${u.id}" ${team.email_ready?'':'disabled'}>Send password reset</button>${u.role!=='owner'?`<button class="secondary" data-team-action="remove" data-id="${u.id}">Remove access</button>`:''}</td></tr>`));
 h+='<h2>Pending invitations</h2>'+table(['Email','Role','Expires','Actions'],team.invites.map(i=>`<tr><td>${escape(i.email)}</td><td>${escape(i.role)}</td><td>${escape(new Date(i.expires_at).toLocaleDateString())}${new Date(i.expires_at)<=new Date()?'<small>Expired</small>':''}</td><td><button class="secondary" data-team-action="link" data-id="${i.id}">Get private link</button><button class="secondary" data-team-action="send" data-id="${i.id}" ${team.email_ready?'':'disabled'}>Send invitation</button><button class="secondary" data-team-action="revoke" data-id="${i.id}">Revoke</button></td></tr>`));
 }else h+='<p>'+ (selectedCompany?'Loading company users...':'Select a company to view its users and pending invitations.')+'</p>';
}
if(view==='emails')h='<div class="panel"><h2>Branded email delivery</h2><p>Notifications use the verified Resend sender. Secure invitations require a separate auth sender with tracking disabled. Supabase password resets are configured separately.</p><button id="checkEmail" class="secondary">Check email configuration</button><p id="emailStatus" role="status"></p><form id="testEmail"><label>Test recipient email<input name="email" type="email" required maxlength="254"></label><button>Send one test email</button></form><p>A test does not create a customer account. Provider acceptance does not guarantee inbox delivery.</p></div>';
if(view==='overview')h=`<div class="cards"><article class="card"><h3>Companies</h3><strong>${data.accounts.length}</strong></article><article class="card"><h3>Open tasks</h3><strong>${data.tasks.filter(t=>t.status!=='done').length}</strong></article><article class="card"><h3>In onboarding</h3><strong>${data.workflows.filter(w=>w.stage!=='live').length}</strong></article></div><div class="panel"><h2>From first conversation to first quote.</h2><p>Keep commercial plans, software access and onboarding progress in one workspace.</p><a href="#guide">View the customer setup workflow →</a></div><div class="panel"><h3>Next actions</h3>${data.tasks.filter(t=>t.status!=='done').slice(0,8).map(t=>`<p><strong>${escape(t.title)}</strong> · ${escape(company(t.account_id))} · ${escape(t.due_date||'No due date')}</p>`).join('')||'<p>No open tasks. Add the next action for your first customer.</p>'}</div>`;
if(view==='accounts'||view==='modules'){h=`<div class="toolbar"><p>Starter: 1 · Growth: 3 · Suite/trial: up to 9. Quoting uses Job Costing access.</p><button data-edit="accounts">New company</button></div>`;h+=table(['Company','Plan / status','Module access','Actions'],data.accounts.map(a=>`<tr><td>${escape(a.name)}</td><td>${escape(a.plan)}<small>${escape(a.status)}</small></td><td>${a.modules.length} enabled<small>${a.modules.map(m=>escape(modules.find(x=>x[0]===m)?.[1]||m)).join(', ')}</small></td><td>${editButton('accounts',a.id,'Manage access')} ${editButton('invite',a.id,'Invite user')} <button class="secondary" data-company-users="${a.id}">Manage users</button></td></tr>`))}
if(view==='contacts'){h='<div class="toolbar"><p>Contact records do not grant software access.</p><button data-edit="contacts">Add contact</button></div>';h+=table(['Contact','Company','Email / phone','Actions'],data.contacts.map(c=>`<tr><td>${escape(c.name)}</td><td>${escape(company(c.account_id))}</td><td>${escape(c.email)}<small>${escape(c.phone)}</small></td><td>${editButton('contacts',c.id)}</td></tr>`))}
if(view==='tasks'){h='<div class="toolbar"><p>Plan work, assign a responsible person and track blockers.</p><button data-edit="tasks">Add task</button></div>';h+=table(['Task','Company','Owner / due','Status','Actions'],data.tasks.map(t=>`<tr><td>${escape(t.title)}</td><td>${escape(company(t.account_id))}</td><td>${escape(t.owner_name)}<small>${escape(t.due_date||'No due date')}</small></td><td>${escape(t.status)}</td><td>${editButton('tasks',t.id)}</td></tr>`))}
if(view==='workflows'){h='<div class="toolbar"><p>Move customers through setup with an explicit next step.</p><button data-edit="workflows">Start onboarding</button></div><div class="board">'+stages.map(stage=>`<section class="lane"><h3>${stage}</h3>${data.workflows.filter(w=>w.stage===stage).map(w=>`<div class="workflow"><strong>${escape(company(w.account_id))}</strong><p>${escape(w.next_step||'Set the next step')}</p><small>${escape(w.owner_name)} · ${escape(w.target_date||'No target date')}</small>${editButton('workflows',w.id,'Update stage')}</div>`).join('')||'<small>No companies in this stage.</small>'}</section>`).join('')+'</div>'}
if(view==='activity')h='<p>Recent database changes. This initial history records what changed and when; named staff attribution will follow individual staff login.</p>'+table(['When','Company','Record','Action'],data.activity.map(a=>`<tr><td>${escape(new Date(a.created_at).toLocaleString())}</td><td>${escape(company(a.account_id))}</td><td>${escape(a.resource)}</td><td>${escape(a.action)}</td></tr>`));
if(view==='guide')h='<div class="panel"><h2>Edward’s setup checklist</h2><p>Waiting for Edward’s email, company, role and starting modules. No invitation has been sent.</p><ol class="steps"><li>Create or select the company. Avoid duplicating an existing Antech workspace.</li><li>Select the plan and allowed modules. Start a 14-day trial when appropriate.</li><li>Add Edward as a contact, then create a software invitation with his confirmed email and role.</li><li>Copy the invitation link and share it securely. Email delivery is not configured yet.</li><li>Start onboarding in Setup. Assign an owner and a training target date.</li><li>Configure company details, machine profile, materials, gas and electricity rates.</li><li>Import a sample Han’s export, check the calculation and save the first quotation/PDF.</li><li>Run a reviewed pilot, resolve blockers, then move the workflow to Live.</li></ol></div><div class="panel"><h3>Architecture</h3><p>This separate staff interface uses the existing protected admin API and Supabase company records. Internal contacts, tasks and workflows are private server-only tables. Customer roles do not grant internal access.</p><p>Plan changes here do not charge a card. Paid Stripe plan changes must go through billing. Module limits are enforced by the server.</p></div>';
$('content').innerHTML=h;}
function input(name,label,value='',type='text',required=false){return `<label>${label}${required?' *':' (optional)'}<input name="${name}" type="${type}" value="${escape(value)}" ${required?'required':''} maxlength="${name==='title'?200:120}"></label>`}
function select(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${escape(v)}" ${v===value?'selected':''}>${escape(l)}</option>`).join('')}</select></label>`}
function open(resource,id){const record=resource==='company-user'?team.users.find(x=>x.id===id):resource==='invite'?data.accounts.find(x=>x.id===id):data[resource]?.find(x=>x.id===id)||{};editing={resource,id};$('editTitle').textContent=resource==='invite'?'Create invitation':(id?'Edit ':'Create ')+(resource==='accounts'?'company':resource==='company-user'?'company user':resource.slice(0,-1));$('formError').textContent='';let f='';
if(resource==='accounts'){f=input('name','Company name',record.name,'text',true)+select('plan','Plan',Object.keys(limits).map(p=>[p,p]),record.plan||'trial')+select('status','Account status',['active','suspended','cancelled'].map(p=>[p,p]),record.status||'active')+'<p>Select modules within the plan limit. Quoting is included with Job Costing.</p>'+modules.map(([m,label,status])=>`<label class="module-option"><input type="checkbox" name="modules" value="${m}" ${(record.modules||[]).includes(m)?'checked':''}><span>${label}<small>${status}</small></span></label>`).join('')}
else if(resource==='company-user'){f=input('full_name','Full name',record.full_name,'text',true)+select('role','Company role',(record.role==='owner'?['owner']:['owner','admin','manager','operator','viewer']).map(r=>[r,r]),record.role)+`<p>Email: ${escape(record.email)}. Passwords are managed by the user through a reset link.</p>`}
else if(resource==='invite'){f=`<p>Invite a user to <strong>${escape(record.name)}</strong>. Create a private link, or email it after the secure auth sender is configured.</p>`+input('email','Email address','','email',true)+select('role','Software role',['owner','admin','manager','operator','viewer'].map(r=>[r,r]),'owner')+`<label><input type="checkbox" name="send_email"> Send invitation email (requires secure auth sender)</label>`}
else{f=select('account_id','Company',...(resource==='workflows'?[[...data.accounts.map(a=>[a.id,a.name])],record.account_id]:[[['','Unassigned'],...data.accounts.map(a=>[a.id,a.name])],record.account_id||'']));if(resource==='contacts')f+=input('name','Name',record.name,'text',true)+input('email','Email',record.email,'email')+input('phone','Phone',record.phone);if(resource==='tasks')f+=input('title','Task',record.title,'text',true)+select('status','Status',['todo','doing','blocked','done'].map(s=>[s,s]),record.status||'todo')+input('owner_name','Responsible person',record.owner_name)+input('due_date','Due date',record.due_date,'date');if(resource==='workflows')f+=select('stage','Stage',stages.map(s=>[s,s]),record.stage||'setup')+input('owner_name','Responsible person',record.owner_name)+input('next_step','Next step',record.next_step)+input('target_date','Target date',record.target_date,'date');}
if(!['invite','workflows','company-user'].includes(resource))f+=`<label>Notes (optional)<textarea name="notes" maxlength="4000">${escape(record.notes)}</textarea></label>`;$('fields').innerHTML=f;$('editor').showModal();}
$('content').addEventListener('change',e=>{if(e.target.id==='teamCompany')loadTeam(e.target.value)});
$('content').addEventListener('click',async e=>{
 const companyButton=e.target.closest('[data-company-users]');if(companyButton){location.hash='users';await loadTeam(companyButton.dataset.companyUsers);return}
 const button=e.target.closest('[data-team-action]');if(!button)return;
 const action=button.dataset.teamAction,id=button.dataset.id;
 const target=['reset','remove'].includes(action)?team.users.find(u=>u.id===id):team.invites.find(i=>i.id===id);
 if(action!=='link'&&!confirm(({reset:'Send a password-reset email to ',remove:'Remove company access for ',revoke:'Revoke the invitation for ',send:'Send an invitation email to '})[action]+target.email+'?'))return;
 button.disabled=true;try{const resource=['link','send','revoke'].includes(action)?'company-invite':action==='reset'?'user-reset':'company-user';const method=['remove','revoke'].includes(action)?'DELETE':'POST';const result=await api(resource,method,{account_id:selectedCompany,send_email:action==='send'},id);$('notice').textContent=result.invite_url?'Private invitation link: '+result.invite_url:result.message||'Company access updated.';if(action==='remove'||action==='revoke')await loadTeam(selectedCompany)}catch(err){$('notice').textContent=err.message}finally{button.disabled=false}
});
$('content').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)open(b.dataset.edit,b.dataset.id)});
$('content').addEventListener('click',async e=>{if(e.target.id!=='checkEmail')return;try{const status=await api('email');$('emailStatus').textContent=`Notifications: ${status.notifications_ready?'configured':'not configured'} | Secure invitations: ${status.invitations_ready?'configured':'not configured'} | Sender: ${status.sender||'none'}`;}catch(err){$('emailStatus').textContent=err.message}});
$('content').addEventListener('submit',async e=>{if(e.target.id!=='testEmail')return;e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const result=await api('email-test','POST',{email:new FormData(e.target).get('email')});$('emailStatus').textContent=result.message}catch(err){$('emailStatus').textContent=err.message}finally{button.disabled=false}});
$('close').onclick=()=>$('editor').close();$('editForm').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;$('formError').textContent='';try{const fd=new FormData(e.target),body=Object.fromEntries(fd);if(editing.resource==='company-user')body.account_id=selectedCompany;if(editing.resource==='accounts'){body.modules=fd.getAll('modules');if(body.modules.length>limits[body.plan])throw Error('Too many modules for this plan.');}if(editing.resource==='invite'){body.account_id=editing.id;body.send_email=fd.get('send_email')==='on';}for(const key of ['account_id','due_date','target_date'])if(body[key]==='')body[key]=null;const result=await api(editing.resource,editing.id&&editing.resource!=='invite'?'PATCH':'POST',body,editing.resource!=='invite'?editing.id:null);$('editor').close();$('notice').textContent='Saved.';if(editing.resource==='invite'){$('notice').innerHTML='<strong>Invitation created. Copy this private link and share it securely:</strong><p class="invite-result"></p>';$('notice').querySelector('p').textContent=result.invite_url;$('notice').append(document.createTextNode(result.email_status==='accepted'?' Email accepted by Resend.':result.email_status==='failed'?' Email failed. The private link is still available.':' No email was sent.'));}await load();if(selectedCompany)await loadTeam(selectedCompany)}catch(err){$('formError').textContent=err.message}finally{$('save').disabled=false}};
// Setup token stays in memory and is removed from the address bar immediately.
let setupToken=null;
function readSetupLink(){const incoming=new URLSearchParams(location.hash.slice(1)).get('setup');if(!incoming)return;setupToken=incoming;history.replaceState(null,'',location.pathname);$('loginTitle').textContent='Create your password.';$('loginDescription').textContent='Activate your approved Ovrendi staff account. Choose a password with at least 12 characters.';$('confirmLabel').hidden=false;$('confirmPassword').required=true;$('staffPassword').minLength=12;$('staffPassword').autocomplete='new-password';$('signIn').textContent='Activate account';}
readSetupLink();addEventListener('hashchange',readSetupLink);
$('showPassword').onclick=()=>{const visible=$('staffPassword').type==='password';$('staffPassword').type=visible?'text':'password';$('showPassword').textContent=visible?'Hide':'Show';$('showPassword').setAttribute('aria-label',visible?'Hide password':'Show password');$('showPassword').setAttribute('aria-pressed',String(visible));};
$('login').onsubmit=async e=>{e.preventDefault();$('signIn').disabled=true;$('loginError').textContent='';try{
 const email=$('staffEmail').value.trim().toLowerCase(),password=$('staffPassword').value;
 if(setupToken){if(password!==$('confirmPassword').value)throw Error('The passwords do not match.');const r=await fetch(API+'?resource=staff-setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:setupToken,email,password})});const result=await r.json();if(!r.ok)throw Error(result.error||'Could not activate account');setupToken=null;$('confirmLabel').hidden=true;$('confirmPassword').required=false;$('confirmPassword').value='';$('staffPassword').autocomplete='current-password';$('loginTitle').textContent='Welcome back.';$('signIn').textContent='Sign in';}
 const session=await authRequest('token?grant_type=password',{email,password});secret=session.access_token;refreshToken=session.refresh_token;$('staffPassword').value='';
 const staff=await api('session');await load();$('signedInEmail').textContent=staff.email;$('gate').hidden=true;$('workspace').hidden=false;
 }catch(err){const token=secret;clearSession(err.message);if(token)authRequest('logout?scope=local',null,token).catch(()=>{});}finally{$('signIn').disabled=false}};
$('refresh').onclick=()=>load().catch(e=>$('notice').textContent=e.message);
$('logout').onclick=async()=>{const token=secret;clearSession();if(token)try{await authRequest('logout?scope=local',null,token)}catch(_){$('loginError').textContent='Signed out here. Server sign-out could not be confirmed.'}};
$('theme').onclick=()=>document.body.classList.toggle('dark');window.addEventListener('hashchange',()=>{if(secret)render()});
})();
