window.mountOvrendiReporting=async(container,api,view,accounts)=>{
const stamp=crypto.randomUUID();container.dataset.reporting=stamp;container.textContent='Loading reports…';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const company=id=>accounts.find(a=>a.id===id)?.name||'Unknown company',date=v=>v?new Date(v).toLocaleString():'Not recorded';
const table=(headers,rows)=>'<div class="table-wrap"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>';
try{const data=await api(view);if(container.dataset.reporting!==stamp||location.hash!=='#'+view)return;
if(view==='customer-activity'){
 container.innerHTML='<p>Recently active = visible app with recent interaction and a heartbeat within five minutes. This is an estimate, not a live connection guarantee. Times use your browser’s timezone. Refresh for an updated snapshot.</p>'+table(['Company / user','Last sign-in','Last app activity','State / page'],data.map(u=>'<tr><td>'+esc(company(u.account_id))+'<small>'+esc(u.full_name||u.email)+'</small></td><td>'+esc(date(u.last_login_at))+'</td><td>'+esc(date(u.last_seen_at))+'</td><td>'+esc(u.recently_active?'Recently active':'Not recently active')+'<small>'+esc(u.page)+'</small></td></tr>'))+'<p>Up to 2,000 company memberships shown. Sign-in time comes from authentication; activity collection begins with this release.</p>';
}else if(view==='web-analytics'){
 const t=data.totals,rate=t.visits?Math.round(1000*t.converted_visits/t.visits)/10:0;
 container.innerHTML='<p>Last 30 days · opted-in visits only · excludes authenticated app pages. Visits are browser-tab sessions, not unique people. Conversions are recorded only after a successful server submission. Ad blockers, consent choices and bots affect coverage.</p><div class="cards"><article class="card"><h3>Page views</h3><strong>'+t.page_views+'</strong></article><article class="card"><h3>Visits</h3><strong>'+t.visits+'</strong></article><article class="card"><h3>Converted visits</h3><strong>'+t.converted_visits+' ('+rate+'%)</strong></article></div><p>Free-trial call-to-action clicks: '+t.cta_clicks+'</p><h2>Forms</h2>'+table(['Form','Visits that started','Visits that completed'],data.forms.map(f=>'<tr><td>'+esc(f.form)+'</td><td>'+f.starts+'</td><td>'+f.successes+'</td></tr>'))+'<h2>Popular pages</h2>'+table(['Page','Views'],data.pages.map(p=>'<tr><td>'+esc(p.page)+'</td><td>'+p.views+'</td></tr>'))+'<h2>Sources</h2>'+table(['Source','Visits'],data.sources.map(s=>'<tr><td>'+esc(s.source)+'</td><td>'+s.visits+'</td></tr>'))+'<h2>Daily trend (UTC)</h2>'+table(['Date','Views','Converted visits'],data.daily.map(d=>'<tr><td>'+esc(d.day)+'</td><td>'+d.views+'</td><td>'+d.conversions+'</td></tr>'));
}else{
 const controls=document.createElement('div');controls.innerHTML='<label>Filter by company, title or status<input id="bugSearch" type="search" placeholder="Search reports"></label><p>Latest 500 reports. Internal notes stay private to staff; customers can see their report’s status.</p>';const results=document.createElement('div');container.replaceChildren(controls,results);
 function draw(){const query=controls.querySelector('input').value.toLowerCase();results.replaceChildren();for(const report of data.filter(b=>(b.title+' '+company(b.account_id)+' '+b.status).toLowerCase().includes(query))){const card=document.createElement('article');card.className='panel';card.innerHTML='<h2>'+esc(report.title)+'</h2><p>'+esc(company(report.account_id))+' · '+esc(date(report.created_at))+'</p><p>Reporter: '+esc(report.user_id)+' · '+esc(report.page)+'</p><p style="white-space:pre-wrap">'+esc(report.details)+'</p><label>Status<select>'+['new','investigating','resolved','closed'].map(s=>'<option '+(report.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select></label><label>Internal notes<textarea maxlength="4000">'+esc(report.staff_notes)+'</textarea></label><button type="button">Save report</button><p role="status"></p>';
 card.querySelector('button').onclick=async e=>{e.target.disabled=true;try{const status=card.querySelector('select').value,staff_notes=card.querySelector('textarea').value;await api('bugs','PATCH',{status,staff_notes},report.id);report.status=status;report.staff_notes=staff_notes;card.querySelector('[role="status"]').textContent='Saved.'}catch(err){card.querySelector('[role="status"]').textContent=err.message}finally{e.target.disabled=false}};results.append(card)}if(!results.children.length)results.textContent='No matching reports.'}
 controls.querySelector('input').oninput=draw;draw();
}
}catch(err){if(container.dataset.reporting===stamp)container.textContent=err.message}
};