
window.mountSales=async(container,api,accounts,onTasksUpdated=async()=>{})=>{
 const token=crypto.randomUUID();container.dataset.sales=token;const live=()=>container.dataset.sales===token&&location.hash==='#sales';
 const labels={lead:'Lead',qualified:'Qualified',demo:'Demo',trial:'Trial',active:'Active',paid:'Paid',lost:'Lost'},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let rows=[],enquiries=[],filter='',owner='',editing=null;const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
 container.textContent='Loading sales pipeline…';
 try{[rows,enquiries]=await Promise.all([api('sales'),api('enquiries')]);if(!live())return;draw()}catch(e){if(live())container.textContent=e.message}
 function draw(){if(!live())return;const overdue=rows.filter(r=>!['paid','lost'].includes(r.stage)&&r.due_date&&r.due_date<today()),unassigned=rows.filter(r=>!['paid','lost'].includes(r.stage)&&!r.owner_name),incoming=enquiries.filter(e=>!rows.some(r=>r.enquiry_id===e.id));
 container.innerHTML=`<p>Latest 1,000 opportunities. Sales stages are staff records, not verified billing or product activity. Moving a stage does not change modules, trials or subscriptions.</p><div class="cards"><article class="card"><h3>Open opportunities</h3><strong>${rows.filter(r=>!['paid','lost'].includes(r.stage)).length}</strong></article><article class="card"><h3>Overdue next actions</h3><strong>${overdue.length}</strong></article><article class="card"><h3>Without an owner</h3><strong>${unassigned.length}</strong></article></div><div class="toolbar"><label>Search opportunities<input id="salesSearch" type="search" value="${esc(filter)}"></label><label>Owner<select id="salesOwner"><option value="">All owners</option>${[...new Set(rows.map(r=>r.owner_name).filter(Boolean))].map(o=>`<option ${o===owner?'selected':''}>${esc(o)}</option>`).join('')}</select></label><button id="newSale">Add opportunity</button></div><p role="status" id="salesNotice"></p><div id="salesEdit"></div><div id="salesBoard" class="sales-board"></div><details class="panel"><summary>Website enquiry inbox · ${incoming.length} not linked</summary><p>Enquiries are not automatically sales leads. Review support and privacy requests before converting. One opportunity per enquiry; converting does not email anyone.</p><div class="sales-inbox">${incoming.map(e=>`<article><h3>${esc(e.company||e.name)}</h3><p>${esc(e.topic)} · ${esc(e.email)}</p><p>${esc(e.message)}</p><button data-convert="${e.id}" class="secondary">Prepare opportunity</button></article>`).join('')||'<p>All loaded enquiries have opportunities.</p>'}</div></details>`;
 container.querySelector('#salesSearch').oninput=e=>{filter=e.target.value;board()};container.querySelector('#salesOwner').onchange=e=>{owner=e.target.value;board()};container.querySelector('#newSale').onclick=()=>edit({id:crypto.randomUUID(),version:0,stage:'lead'});
 container.querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>{const e=enquiries.find(x=>x.id===b.dataset.convert);edit({id:crypto.randomUUID(),version:0,stage:'lead',enquiry_id:e.id,company:e.company||e.name,contact_name:e.name,email:e.email,notes:(e.topic+' enquiry: '+e.message).slice(0,6000),next_action:'Qualify enquiry'})});board();
 }
 function board(){const filtered=rows.filter(r=>[r.company,r.contact_name,r.email,r.next_action].join(' ').toLowerCase().includes(filter.toLowerCase())&&(!owner||r.owner_name===owner));container.querySelector('#salesBoard').innerHTML=Object.entries(labels).map(([stage,label])=>{const items=filtered.filter(r=>r.stage===stage);return `<section class="sales-column"><h2>${label} <small>${items.length}</small></h2>${items.map(r=>`<article class="sales-card"><button data-sale="${r.id}" class="sales-title">${esc(r.company)}</button><p>${esc(r.contact_name||r.email||'No contact yet')}</p><p>${esc(r.owner_name||'Unassigned')} · <span class="${r.due_date&&r.due_date<today()&&!['paid','lost'].includes(r.stage)?'sales-overdue':''}">${esc(r.due_date||'No due date')}</span></p><p>${esc(r.next_action||'Set a next action')}</p>${r.account_id?`<small>Linked: ${esc(accounts.find(a=>a.id===r.account_id)?.name||'Company account')}</small>`:''}<p>Estimate: US$${Number(r.estimated_monthly_usd).toFixed(2)}/month</p></article>`).join('')||'<p class="muted">No matching opportunities</p>'}</section>`}).join('');container.querySelectorAll('[data-sale]').forEach(b=>b.onclick=()=>edit(rows.find(r=>r.id===b.dataset.sale)))}
 function edit(row){editing={...row};const wrap=container.querySelector('#salesEdit');wrap.innerHTML=`<form class="panel" id="saleForm"><h2>${row.version?'Edit':'New'} opportunity</h2><p>Open qualified, demo, trial and active opportunities need an owner, next action and date. Trial, active and paid stages require a linked company. A Paid stage is a manual sales label, not proof of a charge.</p><div class="sales-fields">${[['company','Company / opportunity name',160],['contact_name','Contact name',160],['email','Email',254],['owner_name','Owner',160],['next_action','Next action',300]].map(([key,label,max])=>`<label>${label}${key==='company'?' · required':''}<input name="${key}" maxlength="${max}" ${key==='company'?'required':''} type="${key==='email'?'email':'text'}" value="${esc(row[key])}"></label>`).join('')}<label>Stage<select name="stage">${Object.entries(labels).map(([v,l])=>`<option value="${v}" ${row.stage===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Linked company<select name="account_id"><option value="">Not linked</option>${accounts.map(a=>`<option value="${a.id}" ${row.account_id===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>Next-action due date<input name="due_date" type="date" value="${esc(row.due_date)}"></label><label>Estimated monthly value · USD<input name="estimated_monthly_usd" type="number" min="0" max="9999999999.99" step="0.01" value="${Number(row.estimated_monthly_usd||0)}"></label></div><label>Lost reason · required when Lost<textarea name="lost_reason" maxlength="500">${esc(row.lost_reason)}</textarea></label><label>Internal notes<textarea name="notes" maxlength="6000" rows="4">${esc(row.notes)}</textarea></label><button>Save opportunity</button> <button type="button" id="cancelSale" class="secondary">Close</button><p role="status" id="saleStatus"></p></form><div id="saleDetails"></div>`;
 const form=wrap.querySelector('form');wrap.querySelector('#cancelSale').onclick=()=>{editing=null;wrap.replaceChildren()};form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{const b=Object.fromEntries(new FormData(form));b.account_id||=null;b.due_date||=null;const saved=await api('sales','POST',{...b,id:row.id,version:row.version||0,enquiry_id:row.enquiry_id||null,operation:'save'});if(!live())return;rows=rows.filter(r=>r.id!==saved.id);rows.unshift(saved);draw();edit(saved);container.querySelector('#salesNotice').textContent='Opportunity saved. No email or billing action was performed.'}catch(err){if(live())form.querySelector('#saleStatus').textContent=err.message}finally{button.disabled=false}};
 wrap.scrollIntoView({block:'start',behavior:'instant'});form.elements.company.focus();if(row.version)details(row);
 }
 async function details(row){try{const d=await api('sales','GET',null,row.id);if(!live()||editing?.id!==row.id)return;const area=container.querySelector('#saleDetails');area.innerHTML=`<section class="panel"><h3>Onboarding & follow-up</h3><p>Add four tasks: access now, rates after two days, first quotation after seven days and a pilot review after fourteen days. Existing tasks and company onboarding progress are kept. This does not create an account, change a trial or send invitations.</p><label>Start date<input type="date" id="salesStart" value="${today()}"></label><button id="salesOnboard" ${row.account_id?'':'disabled'}>Add onboarding tasks</button><p role="status" id="onboardNotice"></p><p><a href="#tasks">Open Tasks & planning</a> · <a href="#workflows">Onboarding</a> · <a href="#customer-success">Trial & usage signals</a> · <a href="#accounts">Manage company access</a></p>${d.tasks.map(t=>`<p>${esc(t.title)} · ${esc(t.status)} · ${esc(t.due_date||'No date')}</p>`).join('')}</section><section class="panel"><h3>Stage history</h3>${d.history.map(h=>`<p>${esc(h.from_stage?labels[h.from_stage]:'Created')} → ${esc(labels[h.to_stage])} · ${esc(h.actor_email)} · ${esc(new Date(h.created_at).toLocaleString())}</p>`).join('')||'<p>No stage history.</p>'}</section>`;
 area.querySelector('#salesOnboard').onclick=async e=>{e.target.disabled=true;try{const result=await api('sales','POST',{id:row.id,operation:'onboarding',start_date:area.querySelector('#salesStart').value});if(!live()||editing?.id!==row.id)return;await onTasksUpdated();await details(row);container.querySelector('#onboardNotice').textContent=result.created+' tasks added. Existing tasks were kept.'}catch(err){if(live()&&editing?.id===row.id)area.querySelector('#onboardNotice').textContent=err.message}finally{e.target.disabled=false}};
 }catch(e){if(live()&&editing?.id===row.id)container.querySelector('#saleDetails').textContent=e.message}}
};
